package com.cqqyd2014.hibernate.entities;
// Generated 2017-10-27 7:29:43 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillInfoFb generated by hbm2java
 */
@Entity
@Table(name = "bill_info_fb", schema = "public")
public class BillInfoFb implements java.io.Serializable {

	private String fbUuid;
	private Date receiveDate;
	private String transportBillNo;
	private String statusCode;
	private Date opDate;
	private String memo;

	public BillInfoFb() {
	}

	public BillInfoFb(String fbUuid) {
		this.fbUuid = fbUuid;
	}

	public BillInfoFb(String fbUuid, Date receiveDate, String transportBillNo, String statusCode, Date opDate,
			String memo) {
		this.fbUuid = fbUuid;
		this.receiveDate = receiveDate;
		this.transportBillNo = transportBillNo;
		this.statusCode = statusCode;
		this.opDate = opDate;
		this.memo = memo;
	}

	@Id

	@Column(name = "fb_uuid", unique = true, nullable = false, length = 45)
	public String getFbUuid() {
		return this.fbUuid;
	}

	public void setFbUuid(String fbUuid) {
		this.fbUuid = fbUuid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "receive_date", length = 35)
	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	@Column(name = "transport_bill_no", length = 45)
	public String getTransportBillNo() {
		return this.transportBillNo;
	}

	public void setTransportBillNo(String transportBillNo) {
		this.transportBillNo = transportBillNo;
	}

	@Column(name = "status_code", length = 45)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "op_date", length = 35)
	public Date getOpDate() {
		return this.opDate;
	}

	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}

	@Column(name = "memo", length = 512)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
