package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-13 2:42:12 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ComParCode generated by hbm2java
 */
@Entity
@Table(name = "com_par_code", schema = "public")
public class ComParCode implements java.io.Serializable {

	private ComParCodeId id;
	private String parDesc;
	private String parValue;

	public ComParCode() {
	}

	public ComParCode(ComParCodeId id) {
		this.id = id;
	}

	public ComParCode(ComParCodeId id, String parDesc, String parValue) {
		this.id = id;
		this.parDesc = parDesc;
		this.parValue = parValue;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 45)),
			@AttributeOverride(name = "parCode", column = @Column(name = "par_code", nullable = false, length = 45)) })
	public ComParCodeId getId() {
		return this.id;
	}

	public void setId(ComParCodeId id) {
		this.id = id;
	}

	@Column(name = "par_desc")
	public String getParDesc() {
		return this.parDesc;
	}

	public void setParDesc(String parDesc) {
		this.parDesc = parDesc;
	}

	@Column(name = "par_value", length = 512)
	public String getParValue() {
		return this.parValue;
	}

	public void setParValue(String parValue) {
		this.parValue = parValue;
	}

}
