package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContractD generated by hbm2java
 */
@Entity
@Table(name = "contract_d", schema = "public")
public class ContractD implements java.io.Serializable {

	private ContractDId id;
	private BigDecimal num;
	private BigDecimal price;
	private BigDecimal numIn;
	private BigDecimal numOut;

	public ContractD() {
	}

	public ContractD(ContractDId id) {
		this.id = id;
	}

	public ContractD(ContractDId id, BigDecimal num, BigDecimal price, BigDecimal numIn, BigDecimal numOut) {
		this.id = id;
		this.num = num;
		this.price = price;
		this.numIn = numIn;
		this.numOut = numOut;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "contractNo", column = @Column(name = "contract_no", nullable = false, length = 45)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", nullable = false, length = 45)) })
	public ContractDId getId() {
		return this.id;
	}

	public void setId(ContractDId id) {
		this.id = id;
	}

	@Column(name = "num", precision = 131089, scale = 0)
	public BigDecimal getNum() {
		return this.num;
	}

	public void setNum(BigDecimal num) {
		this.num = num;
	}

	@Column(name = "price", precision = 131089, scale = 0)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "num_in", precision = 131089, scale = 0)
	public BigDecimal getNumIn() {
		return this.numIn;
	}

	public void setNumIn(BigDecimal numIn) {
		this.numIn = numIn;
	}

	@Column(name = "num_out", precision = 131089, scale = 0)
	public BigDecimal getNumOut() {
		return this.numOut;
	}

	public void setNumOut(BigDecimal numOut) {
		this.numOut = numOut;
	}

}
