package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-5 14:48:25 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinanceAccount generated by hbm2java
 */
@Entity
@Table(name = "finance_account", schema = "public")
public class FinanceAccount implements java.io.Serializable {

	private FinanceAccountId id;
	private Date createDat;
	private String accountName;
	private Integer banlanceDirection;
	private Boolean ifLeaf;

	public FinanceAccount() {
	}

	public FinanceAccount(FinanceAccountId id) {
		this.id = id;
	}

	public FinanceAccount(FinanceAccountId id, Date createDat, String accountName, Integer banlanceDirection,
			Boolean ifLeaf) {
		this.id = id;
		this.createDat = createDat;
		this.accountName = accountName;
		this.banlanceDirection = banlanceDirection;
		this.ifLeaf = ifLeaf;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 45)),
			@AttributeOverride(name = "bookId", column = @Column(name = "book_id", nullable = false, length = 45)),
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false, length = 45)) })
	public FinanceAccountId getId() {
		return this.id;
	}

	public void setId(FinanceAccountId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dat", length = 35)
	public Date getCreateDat() {
		return this.createDat;
	}

	public void setCreateDat(Date createDat) {
		this.createDat = createDat;
	}

	@Column(name = "account_name", length = 45)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "banlance_direction")
	public Integer getBanlanceDirection() {
		return this.banlanceDirection;
	}

	public void setBanlanceDirection(Integer banlanceDirection) {
		this.banlanceDirection = banlanceDirection;
	}

	@Column(name = "if_leaf")
	public Boolean getIfLeaf() {
		return this.ifLeaf;
	}

	public void setIfLeaf(Boolean ifLeaf) {
		this.ifLeaf = ifLeaf;
	}

}
