package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-16 20:52:26 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinanceBook generated by hbm2java
 */
@Entity
@Table(name = "finance_book", schema = "public")
public class FinanceBook implements java.io.Serializable {

	private FinanceBookId id;
	private String bookName;
	private Date createDat;

	public FinanceBook() {
	}

	public FinanceBook(FinanceBookId id) {
		this.id = id;
	}

	public FinanceBook(FinanceBookId id, String bookName, Date createDat) {
		this.id = id;
		this.bookName = bookName;
		this.createDat = createDat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 45)),
			@AttributeOverride(name = "bookId", column = @Column(name = "book_id", nullable = false, length = 45)) })
	public FinanceBookId getId() {
		return this.id;
	}

	public void setId(FinanceBookId id) {
		this.id = id;
	}

	@Column(name = "book_name", length = 45)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dat", length = 35)
	public Date getCreateDat() {
		return this.createDat;
	}

	public void setCreateDat(Date createDat) {
		this.createDat = createDat;
	}

}
