package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-5 14:48:25 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoodsMove generated by hbm2java
 */
@Entity
@Table(name = "goods_move", schema = "public")
public class GoodsMove implements java.io.Serializable {

	private GoodsMoveId id;
	private String goodsBarcode;
	private String toWh;
	private Date dat;
	private String fromWh;
	private String moveType;
	private String fromStorage;
	private String toStorage;
	private String userId;

	public GoodsMove() {
	}

	public GoodsMove(GoodsMoveId id, String goodsBarcode, String toWh, Date dat) {
		this.id = id;
		this.goodsBarcode = goodsBarcode;
		this.toWh = toWh;
		this.dat = dat;
	}

	public GoodsMove(GoodsMoveId id, String goodsBarcode, String toWh, Date dat, String fromWh, String moveType,
			String fromStorage, String toStorage, String userId) {
		this.id = id;
		this.goodsBarcode = goodsBarcode;
		this.toWh = toWh;
		this.dat = dat;
		this.fromWh = fromWh;
		this.moveType = moveType;
		this.fromStorage = fromStorage;
		this.toStorage = toStorage;
		this.userId = userId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "moveId", column = @Column(name = "move_id", nullable = false, length = 36)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)) })
	public GoodsMoveId getId() {
		return this.id;
	}

	public void setId(GoodsMoveId id) {
		this.id = id;
	}

	@Column(name = "goods_barcode", nullable = false, length = 22)
	public String getGoodsBarcode() {
		return this.goodsBarcode;
	}

	public void setGoodsBarcode(String goodsBarcode) {
		this.goodsBarcode = goodsBarcode;
	}

	@Column(name = "to_wh", nullable = false, length = 6)
	public String getToWh() {
		return this.toWh;
	}

	public void setToWh(String toWh) {
		this.toWh = toWh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dat", nullable = false, length = 35)
	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

	@Column(name = "from_wh", length = 6)
	public String getFromWh() {
		return this.fromWh;
	}

	public void setFromWh(String fromWh) {
		this.fromWh = fromWh;
	}

	@Column(name = "move_type", length = 4)
	public String getMoveType() {
		return this.moveType;
	}

	public void setMoveType(String moveType) {
		this.moveType = moveType;
	}

	@Column(name = "from_storage", length = 6)
	public String getFromStorage() {
		return this.fromStorage;
	}

	public void setFromStorage(String fromStorage) {
		this.fromStorage = fromStorage;
	}

	@Column(name = "to_storage", length = 6)
	public String getToStorage() {
		return this.toStorage;
	}

	public void setToStorage(String toStorage) {
		this.toStorage = toStorage;
	}

	@Column(name = "user_id", length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
