package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-31 21:46:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GoodsId generated by hbm2java
 */
@Embeddable
public class GoodsId implements java.io.Serializable {

	private String goodsBarcode;
	private String comId;

	public GoodsId() {
	}

	public GoodsId(String goodsBarcode, String comId) {
		this.goodsBarcode = goodsBarcode;
		this.comId = comId;
	}

	@Column(name = "goods_barcode", nullable = false, length = 22)
	public String getGoodsBarcode() {
		return this.goodsBarcode;
	}

	public void setGoodsBarcode(String goodsBarcode) {
		this.goodsBarcode = goodsBarcode;
	}

	@Column(name = "com_id", nullable = false, length = 4)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GoodsId))
			return false;
		GoodsId castOther = (GoodsId) other;

		return ((this.getGoodsBarcode() == castOther.getGoodsBarcode()) || (this.getGoodsBarcode() != null
				&& castOther.getGoodsBarcode() != null && this.getGoodsBarcode().equals(castOther.getGoodsBarcode())))
				&& ((this.getComId() == castOther.getComId()) || (this.getComId() != null
						&& castOther.getComId() != null && this.getComId().equals(castOther.getComId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGoodsBarcode() == null ? 0 : this.getGoodsBarcode().hashCode());
		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		return result;
	}

}
