package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HttpErrorLog generated by hbm2java
 */
@Entity
@Table(name = "http_error_log", schema = "public")
public class HttpErrorLog implements java.io.Serializable {

	private HttpErrorLogId id;
	private String code;
	private String message;
	private String httpUrl;
	private Date opTime;

	public HttpErrorLog() {
	}

	public HttpErrorLog(HttpErrorLogId id) {
		this.id = id;
	}

	public HttpErrorLog(HttpErrorLogId id, String code, String message, String httpUrl, Date opTime) {
		this.id = id;
		this.code = code;
		this.message = message;
		this.httpUrl = httpUrl;
		this.opTime = opTime;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "uuid", column = @Column(name = "uuid", nullable = false, length = 36)) })
	public HttpErrorLogId getId() {
		return this.id;
	}

	public void setId(HttpErrorLogId id) {
		this.id = id;
	}

	@Column(name = "code", length = 128)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "message", length = 1024)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "http_url", length = 1024)
	public String getHttpUrl() {
		return this.httpUrl;
	}

	public void setHttpUrl(String httpUrl) {
		this.httpUrl = httpUrl;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "op_time", length = 15)
	public Date getOpTime() {
		return this.opTime;
	}

	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

}
