package com.cqqyd2014.hibernate.entities;
// Generated 2017-10-27 7:29:43 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HwServLocationId generated by hbm2java
 */
@Embeddable
public class HwServLocationId implements java.io.Serializable {

	private int provinceCode;
	private String comId;

	public HwServLocationId() {
	}

	public HwServLocationId(int provinceCode, String comId) {
		this.provinceCode = provinceCode;
		this.comId = comId;
	}

	@Column(name = "province_code", nullable = false)
	public int getProvinceCode() {
		return this.provinceCode;
	}

	public void setProvinceCode(int provinceCode) {
		this.provinceCode = provinceCode;
	}

	@Column(name = "com_id", nullable = false, length = 45)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HwServLocationId))
			return false;
		HwServLocationId castOther = (HwServLocationId) other;

		return (this.getProvinceCode() == castOther.getProvinceCode())
				&& ((this.getComId() == castOther.getComId()) || (this.getComId() != null
						&& castOther.getComId() != null && this.getComId().equals(castOther.getComId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProvinceCode();
		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		return result;
	}

}
