package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-31 21:46:23 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IntoWhLog generated by hbm2java
 */
@Entity
@Table(name = "into_wh_log", schema = "public")
public class IntoWhLog implements java.io.Serializable {

	private IntoWhLogId id;
	private String goodsId;
	private String type;
	private BigDecimal num;
	private String userId;

	public IntoWhLog() {
	}

	public IntoWhLog(IntoWhLogId id, String goodsId) {
		this.id = id;
		this.goodsId = goodsId;
	}

	public IntoWhLog(IntoWhLogId id, String goodsId, String type, BigDecimal num, String userId) {
		this.id = id;
		this.goodsId = goodsId;
		this.type = type;
		this.num = num;
		this.userId = userId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "uuid", column = @Column(name = "uuid", nullable = false, length = 36)),
			@AttributeOverride(name = "opDate", column = @Column(name = "op_date", nullable = false, length = 35)) })
	public IntoWhLogId getId() {
		return this.id;
	}

	public void setId(IntoWhLogId id) {
		this.id = id;
	}

	@Column(name = "goods_id", nullable = false, length = 45)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "type", length = 4)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "num", precision = 131089, scale = 0)
	public BigDecimal getNum() {
		return this.num;
	}

	public void setNum(BigDecimal num) {
		this.num = num;
	}

	@Column(name = "user_id", length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
