package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-16 20:52:26 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InventoryAjustType generated by hbm2java
 */
@Entity
@Table(name = "inventory_ajust_type", schema = "public")
public class InventoryAjustType implements java.io.Serializable {

	private String ITypeId;
	private String ITypeName;

	public InventoryAjustType() {
	}

	public InventoryAjustType(String ITypeId) {
		this.ITypeId = ITypeId;
	}

	public InventoryAjustType(String ITypeId, String ITypeName) {
		this.ITypeId = ITypeId;
		this.ITypeName = ITypeName;
	}

	@Id

	@Column(name = "i_type_id", unique = true, nullable = false, length = 45)
	public String getITypeId() {
		return this.ITypeId;
	}

	public void setITypeId(String ITypeId) {
		this.ITypeId = ITypeId;
	}

	@Column(name = "i_type_name", length = 45)
	public String getITypeName() {
		return this.ITypeName;
	}

	public void setITypeName(String ITypeName) {
		this.ITypeName = ITypeName;
	}

}
