package com.cqqyd2014.hibernate.entities;
// Generated 2017-10-27 7:29:43 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JmeterInsertData generated by hbm2java
 */
@Entity
@Table(name = "jmeter_insert_data", schema = "public")
public class JmeterInsertData implements java.io.Serializable {

	private String col1;

	public JmeterInsertData() {
	}

	public JmeterInsertData(String col1) {
		this.col1 = col1;
	}

	@Id

	@Column(name = "col1", nullable = false, length = 45)
	public String getCol1() {
		return this.col1;
	}

	public void setCol1(String col1) {
		this.col1 = col1;
	}

}
