package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-13 2:42:12 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LogisticsBillPrintTempletId generated by hbm2java
 */
@Embeddable
public class LogisticsBillPrintTempletId implements java.io.Serializable {

	private String logisticsCode;
	private String logisticsBillCode;

	public LogisticsBillPrintTempletId() {
	}

	public LogisticsBillPrintTempletId(String logisticsCode, String logisticsBillCode) {
		this.logisticsCode = logisticsCode;
		this.logisticsBillCode = logisticsBillCode;
	}

	@Column(name = "logistics_code", nullable = false, length = 10)
	public String getLogisticsCode() {
		return this.logisticsCode;
	}

	public void setLogisticsCode(String logisticsCode) {
		this.logisticsCode = logisticsCode;
	}

	@Column(name = "logistics_bill_code", nullable = false, length = 4)
	public String getLogisticsBillCode() {
		return this.logisticsBillCode;
	}

	public void setLogisticsBillCode(String logisticsBillCode) {
		this.logisticsBillCode = logisticsBillCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogisticsBillPrintTempletId))
			return false;
		LogisticsBillPrintTempletId castOther = (LogisticsBillPrintTempletId) other;

		return ((this.getLogisticsCode() == castOther.getLogisticsCode())
				|| (this.getLogisticsCode() != null && castOther.getLogisticsCode() != null
						&& this.getLogisticsCode().equals(castOther.getLogisticsCode())))
				&& ((this.getLogisticsBillCode() == castOther.getLogisticsBillCode())
						|| (this.getLogisticsBillCode() != null && castOther.getLogisticsBillCode() != null
								&& this.getLogisticsBillCode().equals(castOther.getLogisticsBillCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLogisticsCode() == null ? 0 : this.getLogisticsCode().hashCode());
		result = 37 * result + (getLogisticsBillCode() == null ? 0 : this.getLogisticsBillCode().hashCode());
		return result;
	}

}
