package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrderLog generated by hbm2java
 */
@Entity
@Table(name = "order_log", schema = "public")
public class OrderLog implements java.io.Serializable {

	private OrderLogId id;
	private String type;
	private String memo;
	private String userId;

	public OrderLog() {
	}

	public OrderLog(OrderLogId id) {
		this.id = id;
	}

	public OrderLog(OrderLogId id, String type, String memo, String userId) {
		this.id = id;
		this.type = type;
		this.memo = memo;
		this.userId = userId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderNo", column = @Column(name = "order_no", nullable = false, length = 20)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "opDate", column = @Column(name = "op_date", nullable = false, length = 35)) })
	public OrderLogId getId() {
		return this.id;
	}

	public void setId(OrderLogId id) {
		this.id = id;
	}

	@Column(name = "type", length = 4)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "memo", length = 512)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "user_id", length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
