package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderLogId generated by hbm2java
 */
@Embeddable
public class OrderLogId implements java.io.Serializable {

	private String orderNo;
	private String comId;
	private Date opDate;

	public OrderLogId() {
	}

	public OrderLogId(String orderNo, String comId, Date opDate) {
		this.orderNo = orderNo;
		this.comId = comId;
		this.opDate = opDate;
	}

	@Column(name = "order_no", nullable = false, length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "com_id", nullable = false, length = 4)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "op_date", nullable = false, length = 35)
	public Date getOpDate() {
		return this.opDate;
	}

	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderLogId))
			return false;
		OrderLogId castOther = (OrderLogId) other;

		return ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null
				&& castOther.getOrderNo() != null && this.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getComId() == castOther.getComId()) || (this.getComId() != null
						&& castOther.getComId() != null && this.getComId().equals(castOther.getComId())))
				&& ((this.getOpDate() == castOther.getOpDate()) || (this.getOpDate() != null
						&& castOther.getOpDate() != null && this.getOpDate().equals(castOther.getOpDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result + (getOpDate() == null ? 0 : this.getOpDate().hashCode());
		return result;
	}

}
