package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-2 21:24:22 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrderFromUser generated by hbm2java
 */
@Entity
@Table(name = "order_from_user", schema = "public")
public class OrderFromUser implements java.io.Serializable {

	private OrderFromUserId id;

	public OrderFromUser() {
	}

	public OrderFromUser(OrderFromUserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "orderTypeCode", column = @Column(name = "order_type_code", nullable = false, length = 2)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 36)) })
	public OrderFromUserId getId() {
		return this.id;
	}

	public void setId(OrderFromUserId id) {
		this.id = id;
	}

}
