package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-16 20:52:26 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrePackageD generated by hbm2java
 */
@Entity
@Table(name = "pre_package_d", schema = "public")
public class PrePackageD implements java.io.Serializable {

	private PrePackageDId id;
	private String goodsId;

	public PrePackageD() {
	}

	public PrePackageD(PrePackageDId id) {
		this.id = id;
	}

	public PrePackageD(PrePackageDId id, String goodsId) {
		this.id = id;
		this.goodsId = goodsId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "packageBarcode", column = @Column(name = "package_barcode", nullable = false, length = 18)),
			@AttributeOverride(name = "goodsBarcode", column = @Column(name = "goods_barcode", nullable = false, length = 22)) })
	public PrePackageDId getId() {
		return this.id;
	}

	public void setId(PrePackageDId id) {
		this.id = id;
	}

	@Column(name = "goods_id", length = 45)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

}
