package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrePackageDId generated by hbm2java
 */
@Embeddable
public class PrePackageDId implements java.io.Serializable {

	private String comId;
	private String packageBarcode;
	private String goodsBarcode;

	public PrePackageDId() {
	}

	public PrePackageDId(String comId, String packageBarcode, String goodsBarcode) {
		this.comId = comId;
		this.packageBarcode = packageBarcode;
		this.goodsBarcode = goodsBarcode;
	}

	@Column(name = "com_id", nullable = false, length = 4)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "package_barcode", nullable = false, length = 18)
	public String getPackageBarcode() {
		return this.packageBarcode;
	}

	public void setPackageBarcode(String packageBarcode) {
		this.packageBarcode = packageBarcode;
	}

	@Column(name = "goods_barcode", nullable = false, length = 22)
	public String getGoodsBarcode() {
		return this.goodsBarcode;
	}

	public void setGoodsBarcode(String goodsBarcode) {
		this.goodsBarcode = goodsBarcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrePackageDId))
			return false;
		PrePackageDId castOther = (PrePackageDId) other;

		return ((this.getComId() == castOther.getComId()) || (this.getComId() != null && castOther.getComId() != null
				&& this.getComId().equals(castOther.getComId())))
				&& ((this.getPackageBarcode() == castOther.getPackageBarcode())
						|| (this.getPackageBarcode() != null && castOther.getPackageBarcode() != null
								&& this.getPackageBarcode().equals(castOther.getPackageBarcode())))
				&& ((this.getGoodsBarcode() == castOther.getGoodsBarcode())
						|| (this.getGoodsBarcode() != null && castOther.getGoodsBarcode() != null
								&& this.getGoodsBarcode().equals(castOther.getGoodsBarcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result + (getPackageBarcode() == null ? 0 : this.getPackageBarcode().hashCode());
		result = 37 * result + (getGoodsBarcode() == null ? 0 : this.getGoodsBarcode().hashCode());
		return result;
	}

}
