package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReturnGoods generated by hbm2java
 */
@Entity
@Table(name = "return_goods", schema = "public")
public class ReturnGoods implements java.io.Serializable {

	private ReturnGoodsId id;
	private String orderNo;
	private String goodsBarcode;
	private Date opDat;
	private String returnUserid;
	private String memo;
	private BigDecimal returnPrice;
	private String orderCreateUserid;
	private String goodsId;
	private String seq;

	public ReturnGoods() {
	}

	public ReturnGoods(ReturnGoodsId id) {
		this.id = id;
	}

	public ReturnGoods(ReturnGoodsId id, String orderNo, String goodsBarcode, Date opDat, String returnUserid,
			String memo, BigDecimal returnPrice, String orderCreateUserid, String goodsId, String seq) {
		this.id = id;
		this.orderNo = orderNo;
		this.goodsBarcode = goodsBarcode;
		this.opDat = opDat;
		this.returnUserid = returnUserid;
		this.memo = memo;
		this.returnPrice = returnPrice;
		this.orderCreateUserid = orderCreateUserid;
		this.goodsId = goodsId;
		this.seq = seq;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "uuid", column = @Column(name = "uuid", nullable = false, length = 36)) })
	public ReturnGoodsId getId() {
		return this.id;
	}

	public void setId(ReturnGoodsId id) {
		this.id = id;
	}

	@Column(name = "order_no", length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "goods_barcode", length = 22)
	public String getGoodsBarcode() {
		return this.goodsBarcode;
	}

	public void setGoodsBarcode(String goodsBarcode) {
		this.goodsBarcode = goodsBarcode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "op_dat", length = 35)
	public Date getOpDat() {
		return this.opDat;
	}

	public void setOpDat(Date opDat) {
		this.opDat = opDat;
	}

	@Column(name = "return_userid", length = 36)
	public String getReturnUserid() {
		return this.returnUserid;
	}

	public void setReturnUserid(String returnUserid) {
		this.returnUserid = returnUserid;
	}

	@Column(name = "memo", length = 512)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "return_price", precision = 131089, scale = 0)
	public BigDecimal getReturnPrice() {
		return this.returnPrice;
	}

	public void setReturnPrice(BigDecimal returnPrice) {
		this.returnPrice = returnPrice;
	}

	@Column(name = "order_create_userid", length = 36)
	public String getOrderCreateUserid() {
		return this.orderCreateUserid;
	}

	public void setOrderCreateUserid(String orderCreateUserid) {
		this.orderCreateUserid = orderCreateUserid;
	}

	@Column(name = "goods_id", length = 128)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "seq", length = 4)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

}
