package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SfCityCode generated by hbm2java
 */
@Entity
@Table(name = "sf_city_code", schema = "public")
public class SfCityCode implements java.io.Serializable {

	private String id;
	private String countryName;
	private String provinceName;
	private String cityName;
	private String countyName;
	private String cityCode;

	public SfCityCode() {
	}

	public SfCityCode(String id) {
		this.id = id;
	}

	public SfCityCode(String id, String countryName, String provinceName, String cityName, String countyName,
			String cityCode) {
		this.id = id;
		this.countryName = countryName;
		this.provinceName = provinceName;
		this.cityName = cityName;
		this.countyName = countyName;
		this.cityCode = cityCode;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "country_name", length = 45)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "province_name", length = 45)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "city_name", length = 45)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "county_name", length = 45)
	public String getCountyName() {
		return this.countyName;
	}

	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	@Column(name = "city_code", length = 45)
	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

}
