package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-16 20:52:26 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SfResponseRouteBack generated by hbm2java
 */
@Entity
@Table(name = "sf_response_route_back", schema = "public")
public class SfResponseRouteBack implements java.io.Serializable {

	private SfResponseRouteBackId id;
	private String custId;
	private Date opTime;
	private String mailno;
	private String acceptTime;
	private String acceptAddress;
	private String remark;
	private String opcode;
	private Date acceptTimeDat;
	private Boolean push;

	public SfResponseRouteBack() {
	}

	public SfResponseRouteBack(SfResponseRouteBackId id, String mailno, String acceptTime) {
		this.id = id;
		this.mailno = mailno;
		this.acceptTime = acceptTime;
	}

	public SfResponseRouteBack(SfResponseRouteBackId id, String custId, Date opTime, String mailno, String acceptTime,
			String acceptAddress, String remark, String opcode, Date acceptTimeDat, Boolean push) {
		this.id = id;
		this.custId = custId;
		this.opTime = opTime;
		this.mailno = mailno;
		this.acceptTime = acceptTime;
		this.acceptAddress = acceptAddress;
		this.remark = remark;
		this.opcode = opcode;
		this.acceptTimeDat = acceptTimeDat;
		this.push = push;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "uuid", column = @Column(name = "uuid", nullable = false, length = 36)),
			@AttributeOverride(name = "subUuid", column = @Column(name = "sub_uuid", nullable = false, length = 36)) })
	public SfResponseRouteBackId getId() {
		return this.id;
	}

	public void setId(SfResponseRouteBackId id) {
		this.id = id;
	}

	@Column(name = "cust_id", length = 32)
	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "op_time", length = 35)
	public Date getOpTime() {
		return this.opTime;
	}

	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	@Column(name = "mailno", nullable = false, length = 64)
	public String getMailno() {
		return this.mailno;
	}

	public void setMailno(String mailno) {
		this.mailno = mailno;
	}

	@Column(name = "accept_time", nullable = false, length = 64)
	public String getAcceptTime() {
		return this.acceptTime;
	}

	public void setAcceptTime(String acceptTime) {
		this.acceptTime = acceptTime;
	}

	@Column(name = "accept_address", length = 64)
	public String getAcceptAddress() {
		return this.acceptAddress;
	}

	public void setAcceptAddress(String acceptAddress) {
		this.acceptAddress = acceptAddress;
	}

	@Column(name = "remark", length = 512)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "opcode", length = 32)
	public String getOpcode() {
		return this.opcode;
	}

	public void setOpcode(String opcode) {
		this.opcode = opcode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "accept_time_dat", length = 35)
	public Date getAcceptTimeDat() {
		return this.acceptTimeDat;
	}

	public void setAcceptTimeDat(Date acceptTimeDat) {
		this.acceptTimeDat = acceptTimeDat;
	}

	@Column(name = "push")
	public Boolean getPush() {
		return this.push;
	}

	public void setPush(Boolean push) {
		this.push = push;
	}

}
