package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-13 2:42:12 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SfResponseRouteBackId generated by hbm2java
 */
@Embeddable
public class SfResponseRouteBackId implements java.io.Serializable {

	private String comId;
	private String uuid;
	private String subUuid;

	public SfResponseRouteBackId() {
	}

	public SfResponseRouteBackId(String comId, String uuid, String subUuid) {
		this.comId = comId;
		this.uuid = uuid;
		this.subUuid = subUuid;
	}

	@Column(name = "com_id", nullable = false, length = 4)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "uuid", nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "sub_uuid", nullable = false, length = 36)
	public String getSubUuid() {
		return this.subUuid;
	}

	public void setSubUuid(String subUuid) {
		this.subUuid = subUuid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SfResponseRouteBackId))
			return false;
		SfResponseRouteBackId castOther = (SfResponseRouteBackId) other;

		return ((this.getComId() == castOther.getComId()) || (this.getComId() != null && castOther.getComId() != null
				&& this.getComId().equals(castOther.getComId())))
				&& ((this.getUuid() == castOther.getUuid()) || (this.getUuid() != null && castOther.getUuid() != null
						&& this.getUuid().equals(castOther.getUuid())))
				&& ((this.getSubUuid() == castOther.getSubUuid()) || (this.getSubUuid() != null
						&& castOther.getSubUuid() != null && this.getSubUuid().equals(castOther.getSubUuid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result + (getUuid() == null ? 0 : this.getUuid().hashCode());
		result = 37 * result + (getSubUuid() == null ? 0 : this.getSubUuid().hashCode());
		return result;
	}

}
