package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-2 21:24:22 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SfResponseBack generated by hbm2java
 */
@Entity
@Table(name = "sf_response_back", schema = "public")
public class SfResponseBack implements java.io.Serializable {

	private SfResponseBackId id;
	private String custId;
	private Date opTime;
	private String responseText;
	private String head;
	private String serviceName;

	public SfResponseBack() {
	}

	public SfResponseBack(SfResponseBackId id) {
		this.id = id;
	}

	public SfResponseBack(SfResponseBackId id, String custId, Date opTime, String responseText, String head,
			String serviceName) {
		this.id = id;
		this.custId = custId;
		this.opTime = opTime;
		this.responseText = responseText;
		this.head = head;
		this.serviceName = serviceName;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "uuid", column = @Column(name = "uuid", nullable = false, length = 36)) })
	public SfResponseBackId getId() {
		return this.id;
	}

	public void setId(SfResponseBackId id) {
		this.id = id;
	}

	@Column(name = "cust_id", length = 64)
	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "op_time", length = 35)
	public Date getOpTime() {
		return this.opTime;
	}

	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	@Column(name = "response_text")
	public String getResponseText() {
		return this.responseText;
	}

	public void setResponseText(String responseText) {
		this.responseText = responseText;
	}

	@Column(name = "head", length = 32)
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "service_name", length = 64)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

}
