package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-16 20:52:26 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SnMax generated by hbm2java
 */
@Entity
@Table(name = "sn_max", schema = "public")
public class SnMax implements java.io.Serializable {

	private SnMaxId id;
	private long maxid;

	public SnMax() {
	}

	public SnMax(SnMaxId id, long maxid) {
		this.id = id;
		this.maxid = maxid;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "snType", column = @Column(name = "sn_type", nullable = false, length = 6)),
			@AttributeOverride(name = "dat", column = @Column(name = "dat", nullable = false, length = 13)) })
	public SnMaxId getId() {
		return this.id;
	}

	public void setId(SnMaxId id) {
		this.id = id;
	}

	@Column(name = "maxid", nullable = false)
	public long getMaxid() {
		return this.maxid;
	}

	public void setMaxid(long maxid) {
		this.maxid = maxid;
	}

}
