package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysLog generated by hbm2java
 */
@Entity
@Table(name = "sys_log", schema = "public")
public class SysLog implements java.io.Serializable {

	private String uuid;
	private String userId;
	private Date actionTime;
	private String logMsg;
	private String logType;
	private String comId;

	public SysLog() {
	}

	public SysLog(String uuid, String userId) {
		this.uuid = uuid;
		this.userId = userId;
	}

	public SysLog(String uuid, String userId, Date actionTime, String logMsg, String logType, String comId) {
		this.uuid = uuid;
		this.userId = userId;
		this.actionTime = actionTime;
		this.logMsg = logMsg;
		this.logType = logType;
		this.comId = comId;
	}

	@Id

	@Column(name = "uuid", unique = true, nullable = false, length = 45)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "user_id", nullable = false, length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "action_time", length = 35)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "log_msg")
	public String getLogMsg() {
		return this.logMsg;
	}

	public void setLogMsg(String logMsg) {
		this.logMsg = logMsg;
	}

	@Column(name = "log_type", length = 45)
	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	@Column(name = "com_id", length = 45)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

}
