package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name = "sys_user", schema = "public")
public class SysUser implements java.io.Serializable {

	private SysUserId id;
	private String name;
	private Date createTime;
	private String pwd;
	private String userLogin;
	private String tel;
	private Boolean effective;
	private Boolean online;
	private Date lastOnlineTime;
	private BigDecimal pickupWeighting;
	private BigDecimal sendWeighting;
	private BigDecimal quotaCurrent;
	private BigDecimal quotaAdd;
	private BigDecimal quotaSubtract;
	private BigDecimal quotaFreez;
	private String email;
	private Date lastModifyDat;
	private String lastModifyUuid;

	public SysUser() {
	}

	public SysUser(SysUserId id) {
		this.id = id;
	}

	public SysUser(SysUserId id, String name, Date createTime, String pwd, String userLogin, String tel,
			Boolean effective, Boolean online, Date lastOnlineTime, BigDecimal pickupWeighting,
			BigDecimal sendWeighting, BigDecimal quotaCurrent, BigDecimal quotaAdd, BigDecimal quotaSubtract,
			BigDecimal quotaFreez, String email, Date lastModifyDat, String lastModifyUuid) {
		this.id = id;
		this.name = name;
		this.createTime = createTime;
		this.pwd = pwd;
		this.userLogin = userLogin;
		this.tel = tel;
		this.effective = effective;
		this.online = online;
		this.lastOnlineTime = lastOnlineTime;
		this.pickupWeighting = pickupWeighting;
		this.sendWeighting = sendWeighting;
		this.quotaCurrent = quotaCurrent;
		this.quotaAdd = quotaAdd;
		this.quotaSubtract = quotaSubtract;
		this.quotaFreez = quotaFreez;
		this.email = email;
		this.lastModifyDat = lastModifyDat;
		this.lastModifyUuid = lastModifyUuid;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 45)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 36)) })
	public SysUserId getId() {
		return this.id;
	}

	public void setId(SysUserId id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 35)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "pwd", length = 45)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "user_login", length = 45)
	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	@Column(name = "tel", length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "effective")
	public Boolean getEffective() {
		return this.effective;
	}

	public void setEffective(Boolean effective) {
		this.effective = effective;
	}

	@Column(name = "online")
	public Boolean getOnline() {
		return this.online;
	}

	public void setOnline(Boolean online) {
		this.online = online;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_online_time", length = 35)
	public Date getLastOnlineTime() {
		return this.lastOnlineTime;
	}

	public void setLastOnlineTime(Date lastOnlineTime) {
		this.lastOnlineTime = lastOnlineTime;
	}

	@Column(name = "pickup_weighting", precision = 131089, scale = 0)
	public BigDecimal getPickupWeighting() {
		return this.pickupWeighting;
	}

	public void setPickupWeighting(BigDecimal pickupWeighting) {
		this.pickupWeighting = pickupWeighting;
	}

	@Column(name = "send_weighting", precision = 131089, scale = 0)
	public BigDecimal getSendWeighting() {
		return this.sendWeighting;
	}

	public void setSendWeighting(BigDecimal sendWeighting) {
		this.sendWeighting = sendWeighting;
	}

	@Column(name = "quota_current", precision = 131089, scale = 0)
	public BigDecimal getQuotaCurrent() {
		return this.quotaCurrent;
	}

	public void setQuotaCurrent(BigDecimal quotaCurrent) {
		this.quotaCurrent = quotaCurrent;
	}

	@Column(name = "quota_add", precision = 131089, scale = 0)
	public BigDecimal getQuotaAdd() {
		return this.quotaAdd;
	}

	public void setQuotaAdd(BigDecimal quotaAdd) {
		this.quotaAdd = quotaAdd;
	}

	@Column(name = "quota_subtract", precision = 131089, scale = 0)
	public BigDecimal getQuotaSubtract() {
		return this.quotaSubtract;
	}

	public void setQuotaSubtract(BigDecimal quotaSubtract) {
		this.quotaSubtract = quotaSubtract;
	}

	@Column(name = "quota_freez", precision = 131089, scale = 0)
	public BigDecimal getQuotaFreez() {
		return this.quotaFreez;
	}

	public void setQuotaFreez(BigDecimal quotaFreez) {
		this.quotaFreez = quotaFreez;
	}

	@Column(name = "email", length = 521)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modify_dat", length = 35)
	public Date getLastModifyDat() {
		return this.lastModifyDat;
	}

	public void setLastModifyDat(Date lastModifyDat) {
		this.lastModifyDat = lastModifyDat;
	}

	@Column(name = "last_modify_uuid", length = 36)
	public String getLastModifyUuid() {
		return this.lastModifyUuid;
	}

	public void setLastModifyUuid(String lastModifyUuid) {
		this.lastModifyUuid = lastModifyUuid;
	}

}
