package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-5 14:48:25 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TaobaoGoodsM generated by hbm2java
 */
@Entity
@Table(name = "taobao_goods_m", schema = "public")
public class TaobaoGoodsM implements java.io.Serializable {

	private TaobaoGoodsMId id;

	public TaobaoGoodsM() {
	}

	public TaobaoGoodsM(TaobaoGoodsMId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "GId", column = @Column(name = "g_id", nullable = false, length = 100)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "orderTypeCode", column = @Column(name = "order_type_code", nullable = false, length = 2)) })
	public TaobaoGoodsMId getId() {
		return this.id;
	}

	public void setId(TaobaoGoodsMId id) {
		this.id = id;
	}

}
