package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TaobaoGoodsD generated by hbm2java
 */
@Entity
@Table(name = "taobao_goods_d", schema = "public")
public class TaobaoGoodsD implements java.io.Serializable {

	private TaobaoGoodsDId id;
	private BigDecimal num;

	public TaobaoGoodsD() {
	}

	public TaobaoGoodsD(TaobaoGoodsDId id) {
		this.id = id;
	}

	public TaobaoGoodsD(TaobaoGoodsDId id, BigDecimal num) {
		this.id = id;
		this.num = num;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "GId", column = @Column(name = "g_id", nullable = false, length = 100)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "orderTypeCode", column = @Column(name = "order_type_code", nullable = false, length = 2)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", nullable = false, length = 45)) })
	public TaobaoGoodsDId getId() {
		return this.id;
	}

	public void setId(TaobaoGoodsDId id) {
		this.id = id;
	}

	@Column(name = "num", precision = 131089, scale = 0)
	public BigDecimal getNum() {
		return this.num;
	}

	public void setNum(BigDecimal num) {
		this.num = num;
	}

}
