package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VComInfoId generated by hbm2java
 */
@Embeddable
public class VComInfoId implements java.io.Serializable {

	private String CId;
	private String CName;
	private String orderHead;
	private String contactName;
	private String contactTell;
	private String CShortName;
	private String messageMail;
	private String waringMail;
	private String serviceTell;
	private String seq;
	private Boolean effective;

	public VComInfoId() {
	}

	public VComInfoId(String CId, String CName, String orderHead, String contactName, String contactTell,
			String CShortName, String messageMail, String waringMail, String serviceTell, String seq,
			Boolean effective) {
		this.CId = CId;
		this.CName = CName;
		this.orderHead = orderHead;
		this.contactName = contactName;
		this.contactTell = contactTell;
		this.CShortName = CShortName;
		this.messageMail = messageMail;
		this.waringMail = waringMail;
		this.serviceTell = serviceTell;
		this.seq = seq;
		this.effective = effective;
	}

	@Column(name = "c_id", length = 45)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@Column(name = "c_name", length = 90)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Column(name = "order_head", length = 45)
	public String getOrderHead() {
		return this.orderHead;
	}

	public void setOrderHead(String orderHead) {
		this.orderHead = orderHead;
	}

	@Column(name = "contact_name", length = 45)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_tell", length = 45)
	public String getContactTell() {
		return this.contactTell;
	}

	public void setContactTell(String contactTell) {
		this.contactTell = contactTell;
	}

	@Column(name = "c_short_name", length = 45)
	public String getCShortName() {
		return this.CShortName;
	}

	public void setCShortName(String CShortName) {
		this.CShortName = CShortName;
	}

	@Column(name = "message_mail", length = 90)
	public String getMessageMail() {
		return this.messageMail;
	}

	public void setMessageMail(String messageMail) {
		this.messageMail = messageMail;
	}

	@Column(name = "waring_mail", length = 90)
	public String getWaringMail() {
		return this.waringMail;
	}

	public void setWaringMail(String waringMail) {
		this.waringMail = waringMail;
	}

	@Column(name = "service_tell", length = 45)
	public String getServiceTell() {
		return this.serviceTell;
	}

	public void setServiceTell(String serviceTell) {
		this.serviceTell = serviceTell;
	}

	@Column(name = "seq", length = 4)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "effective")
	public Boolean getEffective() {
		return this.effective;
	}

	public void setEffective(Boolean effective) {
		this.effective = effective;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VComInfoId))
			return false;
		VComInfoId castOther = (VComInfoId) other;

		return ((this.getCId() == castOther.getCId())
				|| (this.getCId() != null && castOther.getCId() != null && this.getCId().equals(castOther.getCId())))
				&& ((this.getCName() == castOther.getCName()) || (this.getCName() != null
						&& castOther.getCName() != null && this.getCName().equals(castOther.getCName())))
				&& ((this.getOrderHead() == castOther.getOrderHead()) || (this.getOrderHead() != null
						&& castOther.getOrderHead() != null && this.getOrderHead().equals(castOther.getOrderHead())))
				&& ((this.getContactName() == castOther.getContactName())
						|| (this.getContactName() != null && castOther.getContactName() != null
								&& this.getContactName().equals(castOther.getContactName())))
				&& ((this.getContactTell() == castOther.getContactTell())
						|| (this.getContactTell() != null && castOther.getContactTell() != null
								&& this.getContactTell().equals(castOther.getContactTell())))
				&& ((this.getCShortName() == castOther.getCShortName()) || (this.getCShortName() != null
						&& castOther.getCShortName() != null && this.getCShortName().equals(castOther.getCShortName())))
				&& ((this.getMessageMail() == castOther.getMessageMail())
						|| (this.getMessageMail() != null && castOther.getMessageMail() != null
								&& this.getMessageMail().equals(castOther.getMessageMail())))
				&& ((this.getWaringMail() == castOther.getWaringMail()) || (this.getWaringMail() != null
						&& castOther.getWaringMail() != null && this.getWaringMail().equals(castOther.getWaringMail())))
				&& ((this.getServiceTell() == castOther.getServiceTell())
						|| (this.getServiceTell() != null && castOther.getServiceTell() != null
								&& this.getServiceTell().equals(castOther.getServiceTell())))
				&& ((this.getSeq() == castOther.getSeq()) || (this.getSeq() != null && castOther.getSeq() != null
						&& this.getSeq().equals(castOther.getSeq())))
				&& ((this.getEffective() == castOther.getEffective()) || (this.getEffective() != null
						&& castOther.getEffective() != null && this.getEffective().equals(castOther.getEffective())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCId() == null ? 0 : this.getCId().hashCode());
		result = 37 * result + (getCName() == null ? 0 : this.getCName().hashCode());
		result = 37 * result + (getOrderHead() == null ? 0 : this.getOrderHead().hashCode());
		result = 37 * result + (getContactName() == null ? 0 : this.getContactName().hashCode());
		result = 37 * result + (getContactTell() == null ? 0 : this.getContactTell().hashCode());
		result = 37 * result + (getCShortName() == null ? 0 : this.getCShortName().hashCode());
		result = 37 * result + (getMessageMail() == null ? 0 : this.getMessageMail().hashCode());
		result = 37 * result + (getWaringMail() == null ? 0 : this.getWaringMail().hashCode());
		result = 37 * result + (getServiceTell() == null ? 0 : this.getServiceTell().hashCode());
		result = 37 * result + (getSeq() == null ? 0 : this.getSeq().hashCode());
		result = 37 * result + (getEffective() == null ? 0 : this.getEffective().hashCode());
		return result;
	}

}
