package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-31 21:46:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VComInfo generated by hbm2java
 */
@Entity
@Table(name = "v_com_info", schema = "public")
public class VComInfo implements java.io.Serializable {

	private VComInfoId id;

	public VComInfo() {
	}

	public VComInfo(VComInfoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "CId", column = @Column(name = "c_id", length = 45)),
			@AttributeOverride(name = "CName", column = @Column(name = "c_name", length = 90)),
			@AttributeOverride(name = "orderHead", column = @Column(name = "order_head", length = 45)),
			@AttributeOverride(name = "contactName", column = @Column(name = "contact_name", length = 45)),
			@AttributeOverride(name = "contactTell", column = @Column(name = "contact_tell", length = 45)),
			@AttributeOverride(name = "CShortName", column = @Column(name = "c_short_name", length = 45)),
			@AttributeOverride(name = "messageMail", column = @Column(name = "message_mail", length = 90)),
			@AttributeOverride(name = "waringMail", column = @Column(name = "waring_mail", length = 90)),
			@AttributeOverride(name = "serviceTell", column = @Column(name = "service_tell", length = 45)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq", length = 4)),
			@AttributeOverride(name = "effective", column = @Column(name = "effective")) })
	public VComInfoId getId() {
		return this.id;
	}

	public void setId(VComInfoId id) {
		this.id = id;
	}

}
