package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-31 21:46:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VContractD generated by hbm2java
 */
@Entity
@Table(name = "v_contract_d", schema = "public")
public class VContractD implements java.io.Serializable {

	private VContractDId id;

	public VContractD() {
	}

	public VContractD(VContractDId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "contractNo", column = @Column(name = "contract_no", length = 45)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", length = 45)),
			@AttributeOverride(name = "num", column = @Column(name = "num", precision = 131089, scale = 0)),
			@AttributeOverride(name = "numIn", column = @Column(name = "num_in", precision = 131089, scale = 0)),
			@AttributeOverride(name = "numOut", column = @Column(name = "num_out", precision = 131089, scale = 0)),
			@AttributeOverride(name = "waiteForArrival", column = @Column(name = "waite_for_arrival", precision = 131089, scale = 0)),
			@AttributeOverride(name = "price", column = @Column(name = "price", precision = 131089, scale = 0)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "CName", column = @Column(name = "c_name", length = 100)),
			@AttributeOverride(name = "unit", column = @Column(name = "unit", length = 45)),
			@AttributeOverride(name = "CUnit", column = @Column(name = "c_unit", length = 90)) })
	public VContractDId getId() {
		return this.id;
	}

	public void setId(VContractDId id) {
		this.id = id;
	}

}
