package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-2 21:24:22 by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VContractMId generated by hbm2java
 */
@Embeddable
public class VContractMId implements java.io.Serializable {

	private String contractNo;
	private String supply;
	private String comId;
	private Date opDat;
	private Date paperDat;
	private Boolean arrival;
	private BigDecimal amount;
	private String supplyName;
	private BigDecimal printCount;
	private Date lastPrintDat;

	public VContractMId() {
	}

	public VContractMId(String contractNo, String supply, String comId, Date opDat, Date paperDat, Boolean arrival,
			BigDecimal amount, String supplyName, BigDecimal printCount, Date lastPrintDat) {
		this.contractNo = contractNo;
		this.supply = supply;
		this.comId = comId;
		this.opDat = opDat;
		this.paperDat = paperDat;
		this.arrival = arrival;
		this.amount = amount;
		this.supplyName = supplyName;
		this.printCount = printCount;
		this.lastPrintDat = lastPrintDat;
	}

	@Column(name = "contract_no", length = 45)
	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Column(name = "supply", length = 45)
	public String getSupply() {
		return this.supply;
	}

	public void setSupply(String supply) {
		this.supply = supply;
	}

	@Column(name = "com_id", length = 4)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "op_dat", length = 35)
	public Date getOpDat() {
		return this.opDat;
	}

	public void setOpDat(Date opDat) {
		this.opDat = opDat;
	}

	@Column(name = "paper_dat", length = 35)
	public Date getPaperDat() {
		return this.paperDat;
	}

	public void setPaperDat(Date paperDat) {
		this.paperDat = paperDat;
	}

	@Column(name = "arrival")
	public Boolean getArrival() {
		return this.arrival;
	}

	public void setArrival(Boolean arrival) {
		this.arrival = arrival;
	}

	@Column(name = "amount", precision = 131089, scale = 0)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "supply_name", length = 45)
	public String getSupplyName() {
		return this.supplyName;
	}

	public void setSupplyName(String supplyName) {
		this.supplyName = supplyName;
	}

	@Column(name = "print_count", precision = 131089, scale = 0)
	public BigDecimal getPrintCount() {
		return this.printCount;
	}

	public void setPrintCount(BigDecimal printCount) {
		this.printCount = printCount;
	}

	@Column(name = "last_print_dat", length = 35)
	public Date getLastPrintDat() {
		return this.lastPrintDat;
	}

	public void setLastPrintDat(Date lastPrintDat) {
		this.lastPrintDat = lastPrintDat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VContractMId))
			return false;
		VContractMId castOther = (VContractMId) other;

		return ((this.getContractNo() == castOther.getContractNo()) || (this.getContractNo() != null
				&& castOther.getContractNo() != null && this.getContractNo().equals(castOther.getContractNo())))
				&& ((this.getSupply() == castOther.getSupply()) || (this.getSupply() != null
						&& castOther.getSupply() != null && this.getSupply().equals(castOther.getSupply())))
				&& ((this.getComId() == castOther.getComId()) || (this.getComId() != null
						&& castOther.getComId() != null && this.getComId().equals(castOther.getComId())))
				&& ((this.getOpDat() == castOther.getOpDat()) || (this.getOpDat() != null
						&& castOther.getOpDat() != null && this.getOpDat().equals(castOther.getOpDat())))
				&& ((this.getPaperDat() == castOther.getPaperDat()) || (this.getPaperDat() != null
						&& castOther.getPaperDat() != null && this.getPaperDat().equals(castOther.getPaperDat())))
				&& ((this.getArrival() == castOther.getArrival()) || (this.getArrival() != null
						&& castOther.getArrival() != null && this.getArrival().equals(castOther.getArrival())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& ((this.getSupplyName() == castOther.getSupplyName()) || (this.getSupplyName() != null
						&& castOther.getSupplyName() != null && this.getSupplyName().equals(castOther.getSupplyName())))
				&& ((this.getPrintCount() == castOther.getPrintCount()) || (this.getPrintCount() != null
						&& castOther.getPrintCount() != null && this.getPrintCount().equals(castOther.getPrintCount())))
				&& ((this.getLastPrintDat() == castOther.getLastPrintDat())
						|| (this.getLastPrintDat() != null && castOther.getLastPrintDat() != null
								&& this.getLastPrintDat().equals(castOther.getLastPrintDat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getContractNo() == null ? 0 : this.getContractNo().hashCode());
		result = 37 * result + (getSupply() == null ? 0 : this.getSupply().hashCode());
		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result + (getOpDat() == null ? 0 : this.getOpDat().hashCode());
		result = 37 * result + (getPaperDat() == null ? 0 : this.getPaperDat().hashCode());
		result = 37 * result + (getArrival() == null ? 0 : this.getArrival().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getSupplyName() == null ? 0 : this.getSupplyName().hashCode());
		result = 37 * result + (getPrintCount() == null ? 0 : this.getPrintCount().hashCode());
		result = 37 * result + (getLastPrintDat() == null ? 0 : this.getLastPrintDat().hashCode());
		return result;
	}

}
