package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VDeliverMId generated by hbm2java
 */
@Embeddable
public class VDeliverMId implements java.io.Serializable {

	private String originalId;
	private String CTell;
	private String tell2;
	private String CStatus;
	private String memoBarcodes;
	private String memoNames;
	private Date packageDat;
	private Date orderDat;
	private String receiverMobile;
	private String userCom;
	private String CUserName;
	private String addrProvince;
	private String addrCity;
	private String addrDistrict;
	private String CUserAddr;
	private String createUserid;
	private String comName;
	private String createUsername;
	private BigDecimal num;
	private String cartonType;
	private BigDecimal cartonWeight;
	private String vehicleId;
	private String vehicleName;
	private String orderNo;
	private String seq;
	private String expressCom;
	private String logisticsName;
	private String expressNo;
	private BigDecimal actualWeight;
	private String deliverNo;
	private String comId;
	private String prePackageBarcode;
	private Boolean effective;
	private Boolean sended;
	private String packageUserid;
	private Date sendDat;
	private BigDecimal packageWeight;
	private String sendUserid;
	private String deliverBillStatus;
	private String whId;
	private String whName;
	private String cancelRequestUserid;
	private String cancelRequestMemo;
	private Date cancelRequestDat;
	private String cancelStatus;
	private Date cancelConfirmDat;
	private String cancelConfirmUserid;
	private String cancelConfirmMemo;
	private String logisticsFbStatus;
	private String logisticsFbMemo;
	private String logisticsFbCode;
	private Date logisticsFbDat;
	private Date sendUserAssignTime;

	public VDeliverMId() {
	}

	public VDeliverMId(String originalId, String CTell, String tell2, String CStatus, String memoBarcodes,
			String memoNames, Date packageDat, Date orderDat, String receiverMobile, String userCom, String CUserName,
			String addrProvince, String addrCity, String addrDistrict, String CUserAddr, String createUserid,
			String comName, String createUsername, BigDecimal num, String cartonType, BigDecimal cartonWeight,
			String vehicleId, String vehicleName, String orderNo, String seq, String expressCom, String logisticsName,
			String expressNo, BigDecimal actualWeight, String deliverNo, String comId, String prePackageBarcode,
			Boolean effective, Boolean sended, String packageUserid, Date sendDat, BigDecimal packageWeight,
			String sendUserid, String deliverBillStatus, String whId, String whName, String cancelRequestUserid,
			String cancelRequestMemo, Date cancelRequestDat, String cancelStatus, Date cancelConfirmDat,
			String cancelConfirmUserid, String cancelConfirmMemo, String logisticsFbStatus, String logisticsFbMemo,
			String logisticsFbCode, Date logisticsFbDat, Date sendUserAssignTime) {
		this.originalId = originalId;
		this.CTell = CTell;
		this.tell2 = tell2;
		this.CStatus = CStatus;
		this.memoBarcodes = memoBarcodes;
		this.memoNames = memoNames;
		this.packageDat = packageDat;
		this.orderDat = orderDat;
		this.receiverMobile = receiverMobile;
		this.userCom = userCom;
		this.CUserName = CUserName;
		this.addrProvince = addrProvince;
		this.addrCity = addrCity;
		this.addrDistrict = addrDistrict;
		this.CUserAddr = CUserAddr;
		this.createUserid = createUserid;
		this.comName = comName;
		this.createUsername = createUsername;
		this.num = num;
		this.cartonType = cartonType;
		this.cartonWeight = cartonWeight;
		this.vehicleId = vehicleId;
		this.vehicleName = vehicleName;
		this.orderNo = orderNo;
		this.seq = seq;
		this.expressCom = expressCom;
		this.logisticsName = logisticsName;
		this.expressNo = expressNo;
		this.actualWeight = actualWeight;
		this.deliverNo = deliverNo;
		this.comId = comId;
		this.prePackageBarcode = prePackageBarcode;
		this.effective = effective;
		this.sended = sended;
		this.packageUserid = packageUserid;
		this.sendDat = sendDat;
		this.packageWeight = packageWeight;
		this.sendUserid = sendUserid;
		this.deliverBillStatus = deliverBillStatus;
		this.whId = whId;
		this.whName = whName;
		this.cancelRequestUserid = cancelRequestUserid;
		this.cancelRequestMemo = cancelRequestMemo;
		this.cancelRequestDat = cancelRequestDat;
		this.cancelStatus = cancelStatus;
		this.cancelConfirmDat = cancelConfirmDat;
		this.cancelConfirmUserid = cancelConfirmUserid;
		this.cancelConfirmMemo = cancelConfirmMemo;
		this.logisticsFbStatus = logisticsFbStatus;
		this.logisticsFbMemo = logisticsFbMemo;
		this.logisticsFbCode = logisticsFbCode;
		this.logisticsFbDat = logisticsFbDat;
		this.sendUserAssignTime = sendUserAssignTime;
	}

	@Column(name = "original_id", length = 45)
	public String getOriginalId() {
		return this.originalId;
	}

	public void setOriginalId(String originalId) {
		this.originalId = originalId;
	}

	@Column(name = "c_tell", length = 45)
	public String getCTell() {
		return this.CTell;
	}

	public void setCTell(String CTell) {
		this.CTell = CTell;
	}

	@Column(name = "tell2", length = 45)
	public String getTell2() {
		return this.tell2;
	}

	public void setTell2(String tell2) {
		this.tell2 = tell2;
	}

	@Column(name = "c_status", length = 4)
	public String getCStatus() {
		return this.CStatus;
	}

	public void setCStatus(String CStatus) {
		this.CStatus = CStatus;
	}

	@Column(name = "memo_barcodes", length = 8000)
	public String getMemoBarcodes() {
		return this.memoBarcodes;
	}

	public void setMemoBarcodes(String memoBarcodes) {
		this.memoBarcodes = memoBarcodes;
	}

	@Column(name = "memo_names", length = 8000)
	public String getMemoNames() {
		return this.memoNames;
	}

	public void setMemoNames(String memoNames) {
		this.memoNames = memoNames;
	}

	@Column(name = "package_dat", length = 35)
	public Date getPackageDat() {
		return this.packageDat;
	}

	public void setPackageDat(Date packageDat) {
		this.packageDat = packageDat;
	}

	@Column(name = "order_dat", length = 35)
	public Date getOrderDat() {
		return this.orderDat;
	}

	public void setOrderDat(Date orderDat) {
		this.orderDat = orderDat;
	}

	@Column(name = "receiver_mobile", length = 45)
	public String getReceiverMobile() {
		return this.receiverMobile;
	}

	public void setReceiverMobile(String receiverMobile) {
		this.receiverMobile = receiverMobile;
	}

	@Column(name = "user_com", length = 45)
	public String getUserCom() {
		return this.userCom;
	}

	public void setUserCom(String userCom) {
		this.userCom = userCom;
	}

	@Column(name = "c_user_name", length = 45)
	public String getCUserName() {
		return this.CUserName;
	}

	public void setCUserName(String CUserName) {
		this.CUserName = CUserName;
	}

	@Column(name = "addr_province", length = 45)
	public String getAddrProvince() {
		return this.addrProvince;
	}

	public void setAddrProvince(String addrProvince) {
		this.addrProvince = addrProvince;
	}

	@Column(name = "addr_city", length = 45)
	public String getAddrCity() {
		return this.addrCity;
	}

	public void setAddrCity(String addrCity) {
		this.addrCity = addrCity;
	}

	@Column(name = "addr_district", length = 45)
	public String getAddrDistrict() {
		return this.addrDistrict;
	}

	public void setAddrDistrict(String addrDistrict) {
		this.addrDistrict = addrDistrict;
	}

	@Column(name = "c_user_addr", length = 450)
	public String getCUserAddr() {
		return this.CUserAddr;
	}

	public void setCUserAddr(String CUserAddr) {
		this.CUserAddr = CUserAddr;
	}

	@Column(name = "create_userid", length = 36)
	public String getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	}

	@Column(name = "com_name", length = 90)
	public String getComName() {
		return this.comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	@Column(name = "create_username", length = 45)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "num", precision = 131089, scale = 0)
	public BigDecimal getNum() {
		return this.num;
	}

	public void setNum(BigDecimal num) {
		this.num = num;
	}

	@Column(name = "carton_type", length = 4)
	public String getCartonType() {
		return this.cartonType;
	}

	public void setCartonType(String cartonType) {
		this.cartonType = cartonType;
	}

	@Column(name = "carton_weight", precision = 131089, scale = 0)
	public BigDecimal getCartonWeight() {
		return this.cartonWeight;
	}

	public void setCartonWeight(BigDecimal cartonWeight) {
		this.cartonWeight = cartonWeight;
	}

	@Column(name = "vehicle_id", length = 4)
	public String getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(String vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "vehicle_name", length = 64)
	public String getVehicleName() {
		return this.vehicleName;
	}

	public void setVehicleName(String vehicleName) {
		this.vehicleName = vehicleName;
	}

	@Column(name = "order_no", length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "seq", length = 4)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "express_com", length = 45)
	public String getExpressCom() {
		return this.expressCom;
	}

	public void setExpressCom(String expressCom) {
		this.expressCom = expressCom;
	}

	@Column(name = "logistics_name", length = 45)
	public String getLogisticsName() {
		return this.logisticsName;
	}

	public void setLogisticsName(String logisticsName) {
		this.logisticsName = logisticsName;
	}

	@Column(name = "express_no", length = 45)
	public String getExpressNo() {
		return this.expressNo;
	}

	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}

	@Column(name = "actual_weight", precision = 131089, scale = 0)
	public BigDecimal getActualWeight() {
		return this.actualWeight;
	}

	public void setActualWeight(BigDecimal actualWeight) {
		this.actualWeight = actualWeight;
	}

	@Column(name = "deliver_no", length = 45)
	public String getDeliverNo() {
		return this.deliverNo;
	}

	public void setDeliverNo(String deliverNo) {
		this.deliverNo = deliverNo;
	}

	@Column(name = "com_id", length = 4)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "pre_package_barcode", length = 18)
	public String getPrePackageBarcode() {
		return this.prePackageBarcode;
	}

	public void setPrePackageBarcode(String prePackageBarcode) {
		this.prePackageBarcode = prePackageBarcode;
	}

	@Column(name = "effective")
	public Boolean getEffective() {
		return this.effective;
	}

	public void setEffective(Boolean effective) {
		this.effective = effective;
	}

	@Column(name = "sended")
	public Boolean getSended() {
		return this.sended;
	}

	public void setSended(Boolean sended) {
		this.sended = sended;
	}

	@Column(name = "package_userid", length = 36)
	public String getPackageUserid() {
		return this.packageUserid;
	}

	public void setPackageUserid(String packageUserid) {
		this.packageUserid = packageUserid;
	}

	@Column(name = "send_dat", length = 35)
	public Date getSendDat() {
		return this.sendDat;
	}

	public void setSendDat(Date sendDat) {
		this.sendDat = sendDat;
	}

	@Column(name = "package_weight", precision = 131089, scale = 0)
	public BigDecimal getPackageWeight() {
		return this.packageWeight;
	}

	public void setPackageWeight(BigDecimal packageWeight) {
		this.packageWeight = packageWeight;
	}

	@Column(name = "send_userid", length = 36)
	public String getSendUserid() {
		return this.sendUserid;
	}

	public void setSendUserid(String sendUserid) {
		this.sendUserid = sendUserid;
	}

	@Column(name = "deliver_bill_status", length = 4)
	public String getDeliverBillStatus() {
		return this.deliverBillStatus;
	}

	public void setDeliverBillStatus(String deliverBillStatus) {
		this.deliverBillStatus = deliverBillStatus;
	}

	@Column(name = "wh_id", length = 6)
	public String getWhId() {
		return this.whId;
	}

	public void setWhId(String whId) {
		this.whId = whId;
	}

	@Column(name = "wh_name")
	public String getWhName() {
		return this.whName;
	}

	public void setWhName(String whName) {
		this.whName = whName;
	}

	@Column(name = "cancel_request_userid", length = 36)
	public String getCancelRequestUserid() {
		return this.cancelRequestUserid;
	}

	public void setCancelRequestUserid(String cancelRequestUserid) {
		this.cancelRequestUserid = cancelRequestUserid;
	}

	@Column(name = "cancel_request_memo", length = 500)
	public String getCancelRequestMemo() {
		return this.cancelRequestMemo;
	}

	public void setCancelRequestMemo(String cancelRequestMemo) {
		this.cancelRequestMemo = cancelRequestMemo;
	}

	@Column(name = "cancel_request_dat", length = 35)
	public Date getCancelRequestDat() {
		return this.cancelRequestDat;
	}

	public void setCancelRequestDat(Date cancelRequestDat) {
		this.cancelRequestDat = cancelRequestDat;
	}

	@Column(name = "cancel_status", length = 4)
	public String getCancelStatus() {
		return this.cancelStatus;
	}

	public void setCancelStatus(String cancelStatus) {
		this.cancelStatus = cancelStatus;
	}

	@Column(name = "cancel_confirm_dat", length = 35)
	public Date getCancelConfirmDat() {
		return this.cancelConfirmDat;
	}

	public void setCancelConfirmDat(Date cancelConfirmDat) {
		this.cancelConfirmDat = cancelConfirmDat;
	}

	@Column(name = "cancel_confirm_userid", length = 36)
	public String getCancelConfirmUserid() {
		return this.cancelConfirmUserid;
	}

	public void setCancelConfirmUserid(String cancelConfirmUserid) {
		this.cancelConfirmUserid = cancelConfirmUserid;
	}

	@Column(name = "cancel_confirm_memo", length = 500)
	public String getCancelConfirmMemo() {
		return this.cancelConfirmMemo;
	}

	public void setCancelConfirmMemo(String cancelConfirmMemo) {
		this.cancelConfirmMemo = cancelConfirmMemo;
	}

	@Column(name = "logistics_fb_status", length = 4)
	public String getLogisticsFbStatus() {
		return this.logisticsFbStatus;
	}

	public void setLogisticsFbStatus(String logisticsFbStatus) {
		this.logisticsFbStatus = logisticsFbStatus;
	}

	@Column(name = "logistics_fb_memo", length = 1024)
	public String getLogisticsFbMemo() {
		return this.logisticsFbMemo;
	}

	public void setLogisticsFbMemo(String logisticsFbMemo) {
		this.logisticsFbMemo = logisticsFbMemo;
	}

	@Column(name = "logistics_fb_code", length = 512)
	public String getLogisticsFbCode() {
		return this.logisticsFbCode;
	}

	public void setLogisticsFbCode(String logisticsFbCode) {
		this.logisticsFbCode = logisticsFbCode;
	}

	@Column(name = "logistics_fb_dat", length = 35)
	public Date getLogisticsFbDat() {
		return this.logisticsFbDat;
	}

	public void setLogisticsFbDat(Date logisticsFbDat) {
		this.logisticsFbDat = logisticsFbDat;
	}

	@Column(name = "send_user_assign_time", length = 35)
	public Date getSendUserAssignTime() {
		return this.sendUserAssignTime;
	}

	public void setSendUserAssignTime(Date sendUserAssignTime) {
		this.sendUserAssignTime = sendUserAssignTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VDeliverMId))
			return false;
		VDeliverMId castOther = (VDeliverMId) other;

		return ((this.getOriginalId() == castOther.getOriginalId()) || (this.getOriginalId() != null
				&& castOther.getOriginalId() != null && this.getOriginalId().equals(castOther.getOriginalId())))
				&& ((this.getCTell() == castOther.getCTell()) || (this.getCTell() != null
						&& castOther.getCTell() != null && this.getCTell().equals(castOther.getCTell())))
				&& ((this.getTell2() == castOther.getTell2()) || (this.getTell2() != null
						&& castOther.getTell2() != null && this.getTell2().equals(castOther.getTell2())))
				&& ((this.getCStatus() == castOther.getCStatus()) || (this.getCStatus() != null
						&& castOther.getCStatus() != null && this.getCStatus().equals(castOther.getCStatus())))
				&& ((this.getMemoBarcodes() == castOther.getMemoBarcodes())
						|| (this.getMemoBarcodes() != null && castOther.getMemoBarcodes() != null
								&& this.getMemoBarcodes().equals(castOther.getMemoBarcodes())))
				&& ((this.getMemoNames() == castOther.getMemoNames()) || (this.getMemoNames() != null
						&& castOther.getMemoNames() != null && this.getMemoNames().equals(castOther.getMemoNames())))
				&& ((this.getPackageDat() == castOther.getPackageDat()) || (this.getPackageDat() != null
						&& castOther.getPackageDat() != null && this.getPackageDat().equals(castOther.getPackageDat())))
				&& ((this.getOrderDat() == castOther.getOrderDat()) || (this.getOrderDat() != null
						&& castOther.getOrderDat() != null && this.getOrderDat().equals(castOther.getOrderDat())))
				&& ((this.getReceiverMobile() == castOther.getReceiverMobile())
						|| (this.getReceiverMobile() != null && castOther.getReceiverMobile() != null
								&& this.getReceiverMobile().equals(castOther.getReceiverMobile())))
				&& ((this.getUserCom() == castOther.getUserCom()) || (this.getUserCom() != null
						&& castOther.getUserCom() != null && this.getUserCom().equals(castOther.getUserCom())))
				&& ((this.getCUserName() == castOther.getCUserName()) || (this.getCUserName() != null
						&& castOther.getCUserName() != null && this.getCUserName().equals(castOther.getCUserName())))
				&& ((this.getAddrProvince() == castOther.getAddrProvince())
						|| (this.getAddrProvince() != null && castOther.getAddrProvince() != null
								&& this.getAddrProvince().equals(castOther.getAddrProvince())))
				&& ((this.getAddrCity() == castOther.getAddrCity()) || (this.getAddrCity() != null
						&& castOther.getAddrCity() != null && this.getAddrCity().equals(castOther.getAddrCity())))
				&& ((this.getAddrDistrict() == castOther.getAddrDistrict())
						|| (this.getAddrDistrict() != null && castOther.getAddrDistrict() != null
								&& this.getAddrDistrict().equals(castOther.getAddrDistrict())))
				&& ((this.getCUserAddr() == castOther.getCUserAddr()) || (this.getCUserAddr() != null
						&& castOther.getCUserAddr() != null && this.getCUserAddr().equals(castOther.getCUserAddr())))
				&& ((this.getCreateUserid() == castOther.getCreateUserid())
						|| (this.getCreateUserid() != null && castOther.getCreateUserid() != null
								&& this.getCreateUserid().equals(castOther.getCreateUserid())))
				&& ((this.getComName() == castOther.getComName()) || (this.getComName() != null
						&& castOther.getComName() != null && this.getComName().equals(castOther.getComName())))
				&& ((this.getCreateUsername() == castOther.getCreateUsername())
						|| (this.getCreateUsername() != null && castOther.getCreateUsername() != null
								&& this.getCreateUsername().equals(castOther.getCreateUsername())))
				&& ((this.getNum() == castOther.getNum()) || (this.getNum() != null && castOther.getNum() != null
						&& this.getNum().equals(castOther.getNum())))
				&& ((this.getCartonType() == castOther.getCartonType()) || (this.getCartonType() != null
						&& castOther.getCartonType() != null && this.getCartonType().equals(castOther.getCartonType())))
				&& ((this.getCartonWeight() == castOther.getCartonWeight())
						|| (this.getCartonWeight() != null && castOther.getCartonWeight() != null
								&& this.getCartonWeight().equals(castOther.getCartonWeight())))
				&& ((this.getVehicleId() == castOther.getVehicleId()) || (this.getVehicleId() != null
						&& castOther.getVehicleId() != null && this.getVehicleId().equals(castOther.getVehicleId())))
				&& ((this.getVehicleName() == castOther.getVehicleName())
						|| (this.getVehicleName() != null && castOther.getVehicleName() != null
								&& this.getVehicleName().equals(castOther.getVehicleName())))
				&& ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null
						&& castOther.getOrderNo() != null && this.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getSeq() == castOther.getSeq()) || (this.getSeq() != null && castOther.getSeq() != null
						&& this.getSeq().equals(castOther.getSeq())))
				&& ((this.getExpressCom() == castOther.getExpressCom()) || (this.getExpressCom() != null
						&& castOther.getExpressCom() != null && this.getExpressCom().equals(castOther.getExpressCom())))
				&& ((this.getLogisticsName() == castOther.getLogisticsName())
						|| (this.getLogisticsName() != null && castOther.getLogisticsName() != null
								&& this.getLogisticsName().equals(castOther.getLogisticsName())))
				&& ((this.getExpressNo() == castOther.getExpressNo()) || (this.getExpressNo() != null
						&& castOther.getExpressNo() != null && this.getExpressNo().equals(castOther.getExpressNo())))
				&& ((this.getActualWeight() == castOther.getActualWeight())
						|| (this.getActualWeight() != null && castOther.getActualWeight() != null
								&& this.getActualWeight().equals(castOther.getActualWeight())))
				&& ((this.getDeliverNo() == castOther.getDeliverNo()) || (this.getDeliverNo() != null
						&& castOther.getDeliverNo() != null && this.getDeliverNo().equals(castOther.getDeliverNo())))
				&& ((this.getComId() == castOther.getComId()) || (this.getComId() != null
						&& castOther.getComId() != null && this.getComId().equals(castOther.getComId())))
				&& ((this.getPrePackageBarcode() == castOther.getPrePackageBarcode())
						|| (this.getPrePackageBarcode() != null && castOther.getPrePackageBarcode() != null
								&& this.getPrePackageBarcode().equals(castOther.getPrePackageBarcode())))
				&& ((this.getEffective() == castOther.getEffective()) || (this.getEffective() != null
						&& castOther.getEffective() != null && this.getEffective().equals(castOther.getEffective())))
				&& ((this.getSended() == castOther.getSended()) || (this.getSended() != null
						&& castOther.getSended() != null && this.getSended().equals(castOther.getSended())))
				&& ((this.getPackageUserid() == castOther.getPackageUserid())
						|| (this.getPackageUserid() != null && castOther.getPackageUserid() != null
								&& this.getPackageUserid().equals(castOther.getPackageUserid())))
				&& ((this.getSendDat() == castOther.getSendDat()) || (this.getSendDat() != null
						&& castOther.getSendDat() != null && this.getSendDat().equals(castOther.getSendDat())))
				&& ((this.getPackageWeight() == castOther.getPackageWeight())
						|| (this.getPackageWeight() != null && castOther.getPackageWeight() != null
								&& this.getPackageWeight().equals(castOther.getPackageWeight())))
				&& ((this.getSendUserid() == castOther.getSendUserid()) || (this.getSendUserid() != null
						&& castOther.getSendUserid() != null && this.getSendUserid().equals(castOther.getSendUserid())))
				&& ((this.getDeliverBillStatus() == castOther.getDeliverBillStatus())
						|| (this.getDeliverBillStatus() != null && castOther.getDeliverBillStatus() != null
								&& this.getDeliverBillStatus().equals(castOther.getDeliverBillStatus())))
				&& ((this.getWhId() == castOther.getWhId()) || (this.getWhId() != null && castOther.getWhId() != null
						&& this.getWhId().equals(castOther.getWhId())))
				&& ((this.getWhName() == castOther.getWhName()) || (this.getWhName() != null
						&& castOther.getWhName() != null && this.getWhName().equals(castOther.getWhName())))
				&& ((this.getCancelRequestUserid() == castOther.getCancelRequestUserid())
						|| (this.getCancelRequestUserid() != null && castOther.getCancelRequestUserid() != null
								&& this.getCancelRequestUserid().equals(castOther.getCancelRequestUserid())))
				&& ((this.getCancelRequestMemo() == castOther.getCancelRequestMemo())
						|| (this.getCancelRequestMemo() != null && castOther.getCancelRequestMemo() != null
								&& this.getCancelRequestMemo().equals(castOther.getCancelRequestMemo())))
				&& ((this.getCancelRequestDat() == castOther.getCancelRequestDat())
						|| (this.getCancelRequestDat() != null && castOther.getCancelRequestDat() != null
								&& this.getCancelRequestDat().equals(castOther.getCancelRequestDat())))
				&& ((this.getCancelStatus() == castOther.getCancelStatus())
						|| (this.getCancelStatus() != null && castOther.getCancelStatus() != null
								&& this.getCancelStatus().equals(castOther.getCancelStatus())))
				&& ((this.getCancelConfirmDat() == castOther.getCancelConfirmDat())
						|| (this.getCancelConfirmDat() != null && castOther.getCancelConfirmDat() != null
								&& this.getCancelConfirmDat().equals(castOther.getCancelConfirmDat())))
				&& ((this.getCancelConfirmUserid() == castOther.getCancelConfirmUserid())
						|| (this.getCancelConfirmUserid() != null && castOther.getCancelConfirmUserid() != null
								&& this.getCancelConfirmUserid().equals(castOther.getCancelConfirmUserid())))
				&& ((this.getCancelConfirmMemo() == castOther.getCancelConfirmMemo())
						|| (this.getCancelConfirmMemo() != null && castOther.getCancelConfirmMemo() != null
								&& this.getCancelConfirmMemo().equals(castOther.getCancelConfirmMemo())))
				&& ((this.getLogisticsFbStatus() == castOther.getLogisticsFbStatus())
						|| (this.getLogisticsFbStatus() != null && castOther.getLogisticsFbStatus() != null
								&& this.getLogisticsFbStatus().equals(castOther.getLogisticsFbStatus())))
				&& ((this.getLogisticsFbMemo() == castOther.getLogisticsFbMemo())
						|| (this.getLogisticsFbMemo() != null && castOther.getLogisticsFbMemo() != null
								&& this.getLogisticsFbMemo().equals(castOther.getLogisticsFbMemo())))
				&& ((this.getLogisticsFbCode() == castOther.getLogisticsFbCode())
						|| (this.getLogisticsFbCode() != null && castOther.getLogisticsFbCode() != null
								&& this.getLogisticsFbCode().equals(castOther.getLogisticsFbCode())))
				&& ((this.getLogisticsFbDat() == castOther.getLogisticsFbDat())
						|| (this.getLogisticsFbDat() != null && castOther.getLogisticsFbDat() != null
								&& this.getLogisticsFbDat().equals(castOther.getLogisticsFbDat())))
				&& ((this.getSendUserAssignTime() == castOther.getSendUserAssignTime())
						|| (this.getSendUserAssignTime() != null && castOther.getSendUserAssignTime() != null
								&& this.getSendUserAssignTime().equals(castOther.getSendUserAssignTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOriginalId() == null ? 0 : this.getOriginalId().hashCode());
		result = 37 * result + (getCTell() == null ? 0 : this.getCTell().hashCode());
		result = 37 * result + (getTell2() == null ? 0 : this.getTell2().hashCode());
		result = 37 * result + (getCStatus() == null ? 0 : this.getCStatus().hashCode());
		result = 37 * result + (getMemoBarcodes() == null ? 0 : this.getMemoBarcodes().hashCode());
		result = 37 * result + (getMemoNames() == null ? 0 : this.getMemoNames().hashCode());
		result = 37 * result + (getPackageDat() == null ? 0 : this.getPackageDat().hashCode());
		result = 37 * result + (getOrderDat() == null ? 0 : this.getOrderDat().hashCode());
		result = 37 * result + (getReceiverMobile() == null ? 0 : this.getReceiverMobile().hashCode());
		result = 37 * result + (getUserCom() == null ? 0 : this.getUserCom().hashCode());
		result = 37 * result + (getCUserName() == null ? 0 : this.getCUserName().hashCode());
		result = 37 * result + (getAddrProvince() == null ? 0 : this.getAddrProvince().hashCode());
		result = 37 * result + (getAddrCity() == null ? 0 : this.getAddrCity().hashCode());
		result = 37 * result + (getAddrDistrict() == null ? 0 : this.getAddrDistrict().hashCode());
		result = 37 * result + (getCUserAddr() == null ? 0 : this.getCUserAddr().hashCode());
		result = 37 * result + (getCreateUserid() == null ? 0 : this.getCreateUserid().hashCode());
		result = 37 * result + (getComName() == null ? 0 : this.getComName().hashCode());
		result = 37 * result + (getCreateUsername() == null ? 0 : this.getCreateUsername().hashCode());
		result = 37 * result + (getNum() == null ? 0 : this.getNum().hashCode());
		result = 37 * result + (getCartonType() == null ? 0 : this.getCartonType().hashCode());
		result = 37 * result + (getCartonWeight() == null ? 0 : this.getCartonWeight().hashCode());
		result = 37 * result + (getVehicleId() == null ? 0 : this.getVehicleId().hashCode());
		result = 37 * result + (getVehicleName() == null ? 0 : this.getVehicleName().hashCode());
		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getSeq() == null ? 0 : this.getSeq().hashCode());
		result = 37 * result + (getExpressCom() == null ? 0 : this.getExpressCom().hashCode());
		result = 37 * result + (getLogisticsName() == null ? 0 : this.getLogisticsName().hashCode());
		result = 37 * result + (getExpressNo() == null ? 0 : this.getExpressNo().hashCode());
		result = 37 * result + (getActualWeight() == null ? 0 : this.getActualWeight().hashCode());
		result = 37 * result + (getDeliverNo() == null ? 0 : this.getDeliverNo().hashCode());
		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result + (getPrePackageBarcode() == null ? 0 : this.getPrePackageBarcode().hashCode());
		result = 37 * result + (getEffective() == null ? 0 : this.getEffective().hashCode());
		result = 37 * result + (getSended() == null ? 0 : this.getSended().hashCode());
		result = 37 * result + (getPackageUserid() == null ? 0 : this.getPackageUserid().hashCode());
		result = 37 * result + (getSendDat() == null ? 0 : this.getSendDat().hashCode());
		result = 37 * result + (getPackageWeight() == null ? 0 : this.getPackageWeight().hashCode());
		result = 37 * result + (getSendUserid() == null ? 0 : this.getSendUserid().hashCode());
		result = 37 * result + (getDeliverBillStatus() == null ? 0 : this.getDeliverBillStatus().hashCode());
		result = 37 * result + (getWhId() == null ? 0 : this.getWhId().hashCode());
		result = 37 * result + (getWhName() == null ? 0 : this.getWhName().hashCode());
		result = 37 * result + (getCancelRequestUserid() == null ? 0 : this.getCancelRequestUserid().hashCode());
		result = 37 * result + (getCancelRequestMemo() == null ? 0 : this.getCancelRequestMemo().hashCode());
		result = 37 * result + (getCancelRequestDat() == null ? 0 : this.getCancelRequestDat().hashCode());
		result = 37 * result + (getCancelStatus() == null ? 0 : this.getCancelStatus().hashCode());
		result = 37 * result + (getCancelConfirmDat() == null ? 0 : this.getCancelConfirmDat().hashCode());
		result = 37 * result + (getCancelConfirmUserid() == null ? 0 : this.getCancelConfirmUserid().hashCode());
		result = 37 * result + (getCancelConfirmMemo() == null ? 0 : this.getCancelConfirmMemo().hashCode());
		result = 37 * result + (getLogisticsFbStatus() == null ? 0 : this.getLogisticsFbStatus().hashCode());
		result = 37 * result + (getLogisticsFbMemo() == null ? 0 : this.getLogisticsFbMemo().hashCode());
		result = 37 * result + (getLogisticsFbCode() == null ? 0 : this.getLogisticsFbCode().hashCode());
		result = 37 * result + (getLogisticsFbDat() == null ? 0 : this.getLogisticsFbDat().hashCode());
		result = 37 * result + (getSendUserAssignTime() == null ? 0 : this.getSendUserAssignTime().hashCode());
		return result;
	}

}
