package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-13 2:42:12 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDeliverdCountSeq generated by hbm2java
 */
@Entity
@Table(name = "v_deliverd_count_seq", schema = "public")
public class VDeliverdCountSeq implements java.io.Serializable {

	private VDeliverdCountSeqId id;

	public VDeliverdCountSeq() {
	}

	public VDeliverdCountSeq(VDeliverdCountSeqId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderNo", column = @Column(name = "order_no", length = 20)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", length = 45)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq", length = 4)),
			@AttributeOverride(name = "num", column = @Column(name = "num")) })
	public VDeliverdCountSeqId getId() {
		return this.id;
	}

	public void setId(VDeliverdCountSeqId id) {
		this.id = id;
	}

}
