package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-5 14:48:25 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDeliverSeq generated by hbm2java
 */
@Entity
@Table(name = "v_deliver_seq", schema = "public")
public class VDeliverSeq implements java.io.Serializable {

	private VDeliverSeqId id;

	public VDeliverSeq() {
	}

	public VDeliverSeq(VDeliverSeqId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "COrderId", column = @Column(name = "c_order_id", length = 45)),
			@AttributeOverride(name = "CGoodsId", column = @Column(name = "c_goods_id", length = 45)),
			@AttributeOverride(name = "sendCount", column = @Column(name = "send_count", precision = 131089, scale = 0)),
			@AttributeOverride(name = "CCount", column = @Column(name = "c_count", precision = 131089, scale = 0)),
			@AttributeOverride(name = "CPrice", column = @Column(name = "c_price", precision = 131089, scale = 0)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq")),
			@AttributeOverride(name = "yue", column = @Column(name = "yue", precision = 131089, scale = 0)),
			@AttributeOverride(name = "CName", column = @Column(name = "c_name", length = 100)),
			@AttributeOverride(name = "unit", column = @Column(name = "unit", length = 90)) })
	public VDeliverSeqId getId() {
		return this.id;
	}

	public void setId(VDeliverSeqId id) {
		this.id = id;
	}

}
