package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VDeliverMMaxId generated by hbm2java
 */
@Embeddable
public class VDeliverMMaxId implements java.io.Serializable {

	private String orderNo;
	private String max;

	public VDeliverMMaxId() {
	}

	public VDeliverMMaxId(String orderNo, String max) {
		this.orderNo = orderNo;
		this.max = max;
	}

	@Column(name = "order_no", length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "max")
	public String getMax() {
		return this.max;
	}

	public void setMax(String max) {
		this.max = max;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VDeliverMMaxId))
			return false;
		VDeliverMMaxId castOther = (VDeliverMMaxId) other;

		return ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null
				&& castOther.getOrderNo() != null && this.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getMax() == castOther.getMax()) || (this.getMax() != null && castOther.getMax() != null
						&& this.getMax().equals(castOther.getMax())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getMax() == null ? 0 : this.getMax().hashCode());
		return result;
	}

}
