package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-31 21:46:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VIntoWhContractDByContractGoods generated by hbm2java
 */
@Entity
@Table(name = "v_into_wh_contract_d_by_contract_goods", schema = "public")
public class VIntoWhContractDByContractGoods implements java.io.Serializable {

	private VIntoWhContractDByContractGoodsId id;

	public VIntoWhContractDByContractGoods() {
	}

	public VIntoWhContractDByContractGoods(VIntoWhContractDByContractGoodsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "contractId", column = @Column(name = "contract_id", length = 45)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", length = 45)),
			@AttributeOverride(name = "sumBuy", column = @Column(name = "sum_buy", precision = 131089, scale = 0)),
			@AttributeOverride(name = "sumOut", column = @Column(name = "sum_out", precision = 131089, scale = 0)),
			@AttributeOverride(name = "sumYue", column = @Column(name = "sum_yue", precision = 131089, scale = 0)) })
	public VIntoWhContractDByContractGoodsId getId() {
		return this.id;
	}

	public void setId(VIntoWhContractDByContractGoodsId id) {
		this.id = id;
	}

}
