package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VInventoryByGoodsIdAvailable generated by hbm2java
 */
@Entity
@Table(name = "v_inventory_by_goods_id_available", schema = "public")
public class VInventoryByGoodsIdAvailable implements java.io.Serializable {

	private VInventoryByGoodsIdAvailableId id;

	public VInventoryByGoodsIdAvailable() {
	}

	public VInventoryByGoodsIdAvailable(VInventoryByGoodsIdAvailableId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 45)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", length = 45)),
			@AttributeOverride(name = "unit", column = @Column(name = "unit", length = 90)),
			@AttributeOverride(name = "CName", column = @Column(name = "c_name", length = 100)),
			@AttributeOverride(name = "sumAvailable", column = @Column(name = "sum_available", precision = 131089, scale = 0)) })
	public VInventoryByGoodsIdAvailableId getId() {
		return this.id;
	}

	public void setId(VInventoryByGoodsIdAvailableId id) {
		this.id = id;
	}

}
