package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VMenuM generated by hbm2java
 */
@Entity
@Table(name = "v_menu_m", schema = "public")
public class VMenuM implements java.io.Serializable {

	private VMenuMId id;

	public VMenuM() {
	}

	public VMenuM(VMenuMId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "menuId", column = @Column(name = "menu_id", length = 4)),
			@AttributeOverride(name = "menuName", column = @Column(name = "menu_name", length = 45)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "desc", column = @Column(name = "desc", length = 45)),
			@AttributeOverride(name = "orderId", column = @Column(name = "order_id", length = 4)) })
	public VMenuMId getId() {
		return this.id;
	}

	public void setId(VMenuMId id) {
		this.id = id;
	}

}
