package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VMenuD generated by hbm2java
 */
@Entity
@Table(name = "v_menu_d", schema = "public")
public class VMenuD implements java.io.Serializable {

	private VMenuDId id;

	public VMenuD() {
	}

	public VMenuD(VMenuDId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "menuId", column = @Column(name = "menu_id", length = 4)),
			@AttributeOverride(name = "menuDId", column = @Column(name = "menu_d_id", length = 4)),
			@AttributeOverride(name = "menuDName", column = @Column(name = "menu_d_name", length = 45)),
			@AttributeOverride(name = "menuDJsMethod", column = @Column(name = "menu_d_js_method", length = 45)),
			@AttributeOverride(name = "menuDJsUrl", column = @Column(name = "menu_d_js_url", length = 256)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "orderId", column = @Column(name = "order_id")),
			@AttributeOverride(name = "webAttention", column = @Column(name = "web_attention")),
			@AttributeOverride(name = "webAttentionTips", column = @Column(name = "web_attention_tips", length = 1024)),
			@AttributeOverride(name = "getNumClass", column = @Column(name = "get_num_class", length = 1024)),
			@AttributeOverride(name = "getNumMethod", column = @Column(name = "get_num_method", length = 1024)) })
	public VMenuDId getId() {
		return this.id;
	}

	public void setId(VMenuDId id) {
		this.id = id;
	}

}
