package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-31 21:46:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VOrderFromId generated by hbm2java
 */
@Embeddable
public class VOrderFromId implements java.io.Serializable {

	private String orderTypeName;
	private String orderTypeDesc;
	private String comId;
	private String seq;
	private String orderTypeCode;
	private String EId;
	private String sender;
	private String senderCom;
	private String senderTell;
	private String senderFullAddr;
	private String senderProvince;
	private String senderCity;
	private String senderDistrict;
	private String senderAddr;
	private String EName;

	public VOrderFromId() {
	}

	public VOrderFromId(String orderTypeName, String orderTypeDesc, String comId, String seq, String orderTypeCode,
			String EId, String sender, String senderCom, String senderTell, String senderFullAddr,
			String senderProvince, String senderCity, String senderDistrict, String senderAddr, String EName) {
		this.orderTypeName = orderTypeName;
		this.orderTypeDesc = orderTypeDesc;
		this.comId = comId;
		this.seq = seq;
		this.orderTypeCode = orderTypeCode;
		this.EId = EId;
		this.sender = sender;
		this.senderCom = senderCom;
		this.senderTell = senderTell;
		this.senderFullAddr = senderFullAddr;
		this.senderProvince = senderProvince;
		this.senderCity = senderCity;
		this.senderDistrict = senderDistrict;
		this.senderAddr = senderAddr;
		this.EName = EName;
	}

	@Column(name = "order_type_name", length = 45)
	public String getOrderTypeName() {
		return this.orderTypeName;
	}

	public void setOrderTypeName(String orderTypeName) {
		this.orderTypeName = orderTypeName;
	}

	@Column(name = "order_type_desc", length = 45)
	public String getOrderTypeDesc() {
		return this.orderTypeDesc;
	}

	public void setOrderTypeDesc(String orderTypeDesc) {
		this.orderTypeDesc = orderTypeDesc;
	}

	@Column(name = "com_id", length = 45)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "seq", length = 4)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "order_type_code", length = 2)
	public String getOrderTypeCode() {
		return this.orderTypeCode;
	}

	public void setOrderTypeCode(String orderTypeCode) {
		this.orderTypeCode = orderTypeCode;
	}

	@Column(name = "e_id", length = 4)
	public String getEId() {
		return this.EId;
	}

	public void setEId(String EId) {
		this.EId = EId;
	}

	@Column(name = "sender", length = 45)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "sender_com", length = 45)
	public String getSenderCom() {
		return this.senderCom;
	}

	public void setSenderCom(String senderCom) {
		this.senderCom = senderCom;
	}

	@Column(name = "sender_tell", length = 45)
	public String getSenderTell() {
		return this.senderTell;
	}

	public void setSenderTell(String senderTell) {
		this.senderTell = senderTell;
	}

	@Column(name = "sender_full_addr", length = 512)
	public String getSenderFullAddr() {
		return this.senderFullAddr;
	}

	public void setSenderFullAddr(String senderFullAddr) {
		this.senderFullAddr = senderFullAddr;
	}

	@Column(name = "sender_province", length = 45)
	public String getSenderProvince() {
		return this.senderProvince;
	}

	public void setSenderProvince(String senderProvince) {
		this.senderProvince = senderProvince;
	}

	@Column(name = "sender_city", length = 45)
	public String getSenderCity() {
		return this.senderCity;
	}

	public void setSenderCity(String senderCity) {
		this.senderCity = senderCity;
	}

	@Column(name = "sender_district", length = 45)
	public String getSenderDistrict() {
		return this.senderDistrict;
	}

	public void setSenderDistrict(String senderDistrict) {
		this.senderDistrict = senderDistrict;
	}

	@Column(name = "sender_addr", length = 256)
	public String getSenderAddr() {
		return this.senderAddr;
	}

	public void setSenderAddr(String senderAddr) {
		this.senderAddr = senderAddr;
	}

	@Column(name = "e_name", length = 45)
	public String getEName() {
		return this.EName;
	}

	public void setEName(String EName) {
		this.EName = EName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VOrderFromId))
			return false;
		VOrderFromId castOther = (VOrderFromId) other;

		return ((this.getOrderTypeName() == castOther.getOrderTypeName())
				|| (this.getOrderTypeName() != null && castOther.getOrderTypeName() != null
						&& this.getOrderTypeName().equals(castOther.getOrderTypeName())))
				&& ((this.getOrderTypeDesc() == castOther.getOrderTypeDesc())
						|| (this.getOrderTypeDesc() != null && castOther.getOrderTypeDesc() != null
								&& this.getOrderTypeDesc().equals(castOther.getOrderTypeDesc())))
				&& ((this.getComId() == castOther.getComId()) || (this.getComId() != null
						&& castOther.getComId() != null && this.getComId().equals(castOther.getComId())))
				&& ((this.getSeq() == castOther.getSeq()) || (this.getSeq() != null && castOther.getSeq() != null
						&& this.getSeq().equals(castOther.getSeq())))
				&& ((this.getOrderTypeCode() == castOther.getOrderTypeCode())
						|| (this.getOrderTypeCode() != null && castOther.getOrderTypeCode() != null
								&& this.getOrderTypeCode().equals(castOther.getOrderTypeCode())))
				&& ((this.getEId() == castOther.getEId()) || (this.getEId() != null && castOther.getEId() != null
						&& this.getEId().equals(castOther.getEId())))
				&& ((this.getSender() == castOther.getSender()) || (this.getSender() != null
						&& castOther.getSender() != null && this.getSender().equals(castOther.getSender())))
				&& ((this.getSenderCom() == castOther.getSenderCom()) || (this.getSenderCom() != null
						&& castOther.getSenderCom() != null && this.getSenderCom().equals(castOther.getSenderCom())))
				&& ((this.getSenderTell() == castOther.getSenderTell()) || (this.getSenderTell() != null
						&& castOther.getSenderTell() != null && this.getSenderTell().equals(castOther.getSenderTell())))
				&& ((this.getSenderFullAddr() == castOther.getSenderFullAddr())
						|| (this.getSenderFullAddr() != null && castOther.getSenderFullAddr() != null
								&& this.getSenderFullAddr().equals(castOther.getSenderFullAddr())))
				&& ((this.getSenderProvince() == castOther.getSenderProvince())
						|| (this.getSenderProvince() != null && castOther.getSenderProvince() != null
								&& this.getSenderProvince().equals(castOther.getSenderProvince())))
				&& ((this.getSenderCity() == castOther.getSenderCity()) || (this.getSenderCity() != null
						&& castOther.getSenderCity() != null && this.getSenderCity().equals(castOther.getSenderCity())))
				&& ((this.getSenderDistrict() == castOther.getSenderDistrict())
						|| (this.getSenderDistrict() != null && castOther.getSenderDistrict() != null
								&& this.getSenderDistrict().equals(castOther.getSenderDistrict())))
				&& ((this.getSenderAddr() == castOther.getSenderAddr()) || (this.getSenderAddr() != null
						&& castOther.getSenderAddr() != null && this.getSenderAddr().equals(castOther.getSenderAddr())))
				&& ((this.getEName() == castOther.getEName()) || (this.getEName() != null
						&& castOther.getEName() != null && this.getEName().equals(castOther.getEName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderTypeName() == null ? 0 : this.getOrderTypeName().hashCode());
		result = 37 * result + (getOrderTypeDesc() == null ? 0 : this.getOrderTypeDesc().hashCode());
		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result + (getSeq() == null ? 0 : this.getSeq().hashCode());
		result = 37 * result + (getOrderTypeCode() == null ? 0 : this.getOrderTypeCode().hashCode());
		result = 37 * result + (getEId() == null ? 0 : this.getEId().hashCode());
		result = 37 * result + (getSender() == null ? 0 : this.getSender().hashCode());
		result = 37 * result + (getSenderCom() == null ? 0 : this.getSenderCom().hashCode());
		result = 37 * result + (getSenderTell() == null ? 0 : this.getSenderTell().hashCode());
		result = 37 * result + (getSenderFullAddr() == null ? 0 : this.getSenderFullAddr().hashCode());
		result = 37 * result + (getSenderProvince() == null ? 0 : this.getSenderProvince().hashCode());
		result = 37 * result + (getSenderCity() == null ? 0 : this.getSenderCity().hashCode());
		result = 37 * result + (getSenderDistrict() == null ? 0 : this.getSenderDistrict().hashCode());
		result = 37 * result + (getSenderAddr() == null ? 0 : this.getSenderAddr().hashCode());
		result = 37 * result + (getEName() == null ? 0 : this.getEName().hashCode());
		return result;
	}

}
