package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-13 2:42:12 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VOrderMainGoodsBarcode generated by hbm2java
 */
@Entity
@Table(name = "v_order_main_goods_barcode", schema = "public")
public class VOrderMainGoodsBarcode implements java.io.Serializable {

	private VOrderMainGoodsBarcodeId id;

	public VOrderMainGoodsBarcode() {
	}

	public VOrderMainGoodsBarcode(VOrderMainGoodsBarcodeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sysUserName", column = @Column(name = "sys_user_name", length = 45)),
			@AttributeOverride(name = "orderVehicleId", column = @Column(name = "order_vehicle_id", length = 4)),
			@AttributeOverride(name = "orderVehicleVechicleName", column = @Column(name = "order_vehicle_vechicle_name", length = 64)),
			@AttributeOverride(name = "orderExpressCom", column = @Column(name = "order_express_com", length = 45)),
			@AttributeOverride(name = "orderExpressComName", column = @Column(name = "order_express_com_name", length = 45)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", length = 36)),
			@AttributeOverride(name = "deliverWhId", column = @Column(name = "deliver_wh_id")),
			@AttributeOverride(name = "deliverWhName", column = @Column(name = "deliver_wh_name")),
			@AttributeOverride(name = "detailMemo", column = @Column(name = "detail_memo")),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "orderNo", column = @Column(name = "order_no", length = 20)),
			@AttributeOverride(name = "CUserName", column = @Column(name = "c_user_name", length = 45)),
			@AttributeOverride(name = "addrProvince", column = @Column(name = "addr_province", length = 45)),
			@AttributeOverride(name = "addrCity", column = @Column(name = "addr_city", length = 45)),
			@AttributeOverride(name = "addrDistrict", column = @Column(name = "addr_district", length = 45)),
			@AttributeOverride(name = "orderDat", column = @Column(name = "order_dat", length = 35)),
			@AttributeOverride(name = "CStatus", column = @Column(name = "c_status", length = 4)),
			@AttributeOverride(name = "gtStatus", column = @Column(name = "gt_status", length = 4)),
			@AttributeOverride(name = "emsStatus", column = @Column(name = "ems_status", length = 4)),
			@AttributeOverride(name = "orderTypeName", column = @Column(name = "order_type_name", length = 4)),
			@AttributeOverride(name = "orderTypeFullName", column = @Column(name = "order_type_full_name", length = 45)),
			@AttributeOverride(name = "packageUser", column = @Column(name = "package_user")),
			@AttributeOverride(name = "originalId", column = @Column(name = "original_id", length = 45)),
			@AttributeOverride(name = "deliverNo", column = @Column(name = "deliver_no")),
			@AttributeOverride(name = "deliverBillStatus", column = @Column(name = "deliver_bill_status")),
			@AttributeOverride(name = "goodsBarcode", column = @Column(name = "goods_barcode")),
			@AttributeOverride(name = "CTell", column = @Column(name = "c_tell", length = 45)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id")),
			@AttributeOverride(name = "deliverExpressNo", column = @Column(name = "deliver_express_no")),
			@AttributeOverride(name = "deliverExpressComName", column = @Column(name = "deliver_express_com_name")),
			@AttributeOverride(name = "deliverExpressCom", column = @Column(name = "deliver_express_com")),
			@AttributeOverride(name = "deliverExpressVehicle", column = @Column(name = "deliver_express_vehicle")),
			@AttributeOverride(name = "CName", column = @Column(name = "c_name")) })
	public VOrderMainGoodsBarcodeId getId() {
		return this.id;
	}

	public void setId(VOrderMainGoodsBarcodeId id) {
		this.id = id;
	}

}
