package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-13 2:42:12 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VOrderFromUserLenId generated by hbm2java
 */
@Embeddable
public class VOrderFromUserLenId implements java.io.Serializable {

	private String EName;
	private String EId;
	private String orderTypeName;
	private String orderTypeDesc;
	private String seq;
	private String comId;
	private String orderTypeCode;
	private String userId;
	private Integer orderNoLen;

	public VOrderFromUserLenId() {
	}

	public VOrderFromUserLenId(String EName, String EId, String orderTypeName, String orderTypeDesc, String seq,
			String comId, String orderTypeCode, String userId, Integer orderNoLen) {
		this.EName = EName;
		this.EId = EId;
		this.orderTypeName = orderTypeName;
		this.orderTypeDesc = orderTypeDesc;
		this.seq = seq;
		this.comId = comId;
		this.orderTypeCode = orderTypeCode;
		this.userId = userId;
		this.orderNoLen = orderNoLen;
	}

	@Column(name = "e_name", length = 45)
	public String getEName() {
		return this.EName;
	}

	public void setEName(String EName) {
		this.EName = EName;
	}

	@Column(name = "e_id", length = 4)
	public String getEId() {
		return this.EId;
	}

	public void setEId(String EId) {
		this.EId = EId;
	}

	@Column(name = "order_type_name", length = 45)
	public String getOrderTypeName() {
		return this.orderTypeName;
	}

	public void setOrderTypeName(String orderTypeName) {
		this.orderTypeName = orderTypeName;
	}

	@Column(name = "order_type_desc", length = 45)
	public String getOrderTypeDesc() {
		return this.orderTypeDesc;
	}

	public void setOrderTypeDesc(String orderTypeDesc) {
		this.orderTypeDesc = orderTypeDesc;
	}

	@Column(name = "seq", length = 4)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "com_id", length = 45)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "order_type_code", length = 2)
	public String getOrderTypeCode() {
		return this.orderTypeCode;
	}

	public void setOrderTypeCode(String orderTypeCode) {
		this.orderTypeCode = orderTypeCode;
	}

	@Column(name = "user_id", length = 36)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "order_no_len")
	public Integer getOrderNoLen() {
		return this.orderNoLen;
	}

	public void setOrderNoLen(Integer orderNoLen) {
		this.orderNoLen = orderNoLen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VOrderFromUserLenId))
			return false;
		VOrderFromUserLenId castOther = (VOrderFromUserLenId) other;

		return ((this.getEName() == castOther.getEName()) || (this.getEName() != null && castOther.getEName() != null
				&& this.getEName().equals(castOther.getEName())))
				&& ((this.getEId() == castOther.getEId()) || (this.getEId() != null && castOther.getEId() != null
						&& this.getEId().equals(castOther.getEId())))
				&& ((this.getOrderTypeName() == castOther.getOrderTypeName())
						|| (this.getOrderTypeName() != null && castOther.getOrderTypeName() != null
								&& this.getOrderTypeName().equals(castOther.getOrderTypeName())))
				&& ((this.getOrderTypeDesc() == castOther.getOrderTypeDesc())
						|| (this.getOrderTypeDesc() != null && castOther.getOrderTypeDesc() != null
								&& this.getOrderTypeDesc().equals(castOther.getOrderTypeDesc())))
				&& ((this.getSeq() == castOther.getSeq()) || (this.getSeq() != null && castOther.getSeq() != null
						&& this.getSeq().equals(castOther.getSeq())))
				&& ((this.getComId() == castOther.getComId()) || (this.getComId() != null
						&& castOther.getComId() != null && this.getComId().equals(castOther.getComId())))
				&& ((this.getOrderTypeCode() == castOther.getOrderTypeCode())
						|| (this.getOrderTypeCode() != null && castOther.getOrderTypeCode() != null
								&& this.getOrderTypeCode().equals(castOther.getOrderTypeCode())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getOrderNoLen() == castOther.getOrderNoLen())
						|| (this.getOrderNoLen() != null && castOther.getOrderNoLen() != null
								&& this.getOrderNoLen().equals(castOther.getOrderNoLen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEName() == null ? 0 : this.getEName().hashCode());
		result = 37 * result + (getEId() == null ? 0 : this.getEId().hashCode());
		result = 37 * result + (getOrderTypeName() == null ? 0 : this.getOrderTypeName().hashCode());
		result = 37 * result + (getOrderTypeDesc() == null ? 0 : this.getOrderTypeDesc().hashCode());
		result = 37 * result + (getSeq() == null ? 0 : this.getSeq().hashCode());
		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result + (getOrderTypeCode() == null ? 0 : this.getOrderTypeCode().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getOrderNoLen() == null ? 0 : this.getOrderNoLen().hashCode());
		return result;
	}

}
