package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-31 21:46:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VOrderFrom generated by hbm2java
 */
@Entity
@Table(name = "v_order_from", schema = "public")
public class VOrderFrom implements java.io.Serializable {

	private VOrderFromId id;

	public VOrderFrom() {
	}

	public VOrderFrom(VOrderFromId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderTypeName", column = @Column(name = "order_type_name", length = 45)),
			@AttributeOverride(name = "orderTypeDesc", column = @Column(name = "order_type_desc", length = 45)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 45)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq", length = 4)),
			@AttributeOverride(name = "orderTypeCode", column = @Column(name = "order_type_code", length = 2)),
			@AttributeOverride(name = "EId", column = @Column(name = "e_id", length = 4)),
			@AttributeOverride(name = "sender", column = @Column(name = "sender", length = 45)),
			@AttributeOverride(name = "senderCom", column = @Column(name = "sender_com", length = 45)),
			@AttributeOverride(name = "senderTell", column = @Column(name = "sender_tell", length = 45)),
			@AttributeOverride(name = "senderFullAddr", column = @Column(name = "sender_full_addr", length = 512)),
			@AttributeOverride(name = "senderProvince", column = @Column(name = "sender_province", length = 45)),
			@AttributeOverride(name = "senderCity", column = @Column(name = "sender_city", length = 45)),
			@AttributeOverride(name = "senderDistrict", column = @Column(name = "sender_district", length = 45)),
			@AttributeOverride(name = "senderAddr", column = @Column(name = "sender_addr", length = 256)),
			@AttributeOverride(name = "EName", column = @Column(name = "e_name", length = 45)) })
	public VOrderFromId getId() {
		return this.id;
	}

	public void setId(VOrderFromId id) {
		this.id = id;
	}

}
