package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-2 21:24:22 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VPickupYueAll generated by hbm2java
 */
@Entity
@Table(name = "v_pickup_yue_all", schema = "public")
public class VPickupYueAll implements java.io.Serializable {

	private VPickupYueAllId id;

	public VPickupYueAll() {
	}

	public VPickupYueAll(VPickupYueAllId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "orderNo", column = @Column(name = "order_no", length = 45)),
			@AttributeOverride(name = "yue", column = @Column(name = "yue", precision = 131089, scale = 0)) })
	public VPickupYueAllId getId() {
		return this.id;
	}

	public void setId(VPickupYueAllId id) {
		this.id = id;
	}

}
