package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-31 21:46:23 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VPickupedCount generated by hbm2java
 */
@Entity
@Table(name = "v_pickuped_count", schema = "public")
public class VPickupedCount implements java.io.Serializable {

	private VPickupedCountId id;

	public VPickupedCount() {
	}

	public VPickupedCount(VPickupedCountId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "orderNo", column = @Column(name = "order_no", length = 20)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", length = 45)),
			@AttributeOverride(name = "num", column = @Column(name = "num")) })
	public VPickupedCountId getId() {
		return this.id;
	}

	public void setId(VPickupedCountId id) {
		this.id = id;
	}

}
