package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-19 15:08:19 by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VReturnGoods generated by hbm2java
 */
@Entity
@Table(name = "v_return_goods", schema = "public")
public class VReturnGoods implements java.io.Serializable {

	private VReturnGoodsId id;

	public VReturnGoods() {
	}

	public VReturnGoods(VReturnGoodsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "uuid", column = @Column(name = "uuid", length = 36)),
			@AttributeOverride(name = "orderNo", column = @Column(name = "order_no", length = 20)),
			@AttributeOverride(name = "goodsBarcode", column = @Column(name = "goods_barcode", length = 22)),
			@AttributeOverride(name = "opDat", column = @Column(name = "op_dat", length = 35)),
			@AttributeOverride(name = "returnUserid", column = @Column(name = "return_userid", length = 36)),
			@AttributeOverride(name = "memo", column = @Column(name = "memo", length = 512)),
			@AttributeOverride(name = "returnPrice", column = @Column(name = "return_price", precision = 131089, scale = 0)),
			@AttributeOverride(name = "orderCreateUserid", column = @Column(name = "order_create_userid", length = 36)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", length = 128)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq", length = 4)),
			@AttributeOverride(name = "CName", column = @Column(name = "c_name", length = 100)),
			@AttributeOverride(name = "returnUsername", column = @Column(name = "return_username", length = 45)),
			@AttributeOverride(name = "orderCreateUsername", column = @Column(name = "order_create_username", length = 45)) })
	public VReturnGoodsId getId() {
		return this.id;
	}

	public void setId(VReturnGoodsId id) {
		this.id = id;
	}

}
