package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VSysUser generated by hbm2java
 */
@Entity
@Table(name = "v_sys_user", schema = "public")
public class VSysUser implements java.io.Serializable {

	private VSysUserId id;

	public VSysUser() {
	}

	public VSysUser(VSysUserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", length = 36)),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 45)),
			@AttributeOverride(name = "createTime", column = @Column(name = "create_time", length = 35)),
			@AttributeOverride(name = "pwd", column = @Column(name = "pwd", length = 45)),
			@AttributeOverride(name = "userLogin", column = @Column(name = "user_login", length = 45)),
			@AttributeOverride(name = "tel", column = @Column(name = "tel", length = 45)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 45)),
			@AttributeOverride(name = "effective", column = @Column(name = "effective")),
			@AttributeOverride(name = "online", column = @Column(name = "online")),
			@AttributeOverride(name = "lastOnlineTime", column = @Column(name = "last_online_time", length = 35)),
			@AttributeOverride(name = "pickupWeighting", column = @Column(name = "pickup_weighting", precision = 131089, scale = 0)),
			@AttributeOverride(name = "sendWeighting", column = @Column(name = "send_weighting", precision = 131089, scale = 0)),
			@AttributeOverride(name = "quotaCurrent", column = @Column(name = "quota_current", precision = 131089, scale = 0)),
			@AttributeOverride(name = "quotaAdd", column = @Column(name = "quota_add", precision = 131089, scale = 0)),
			@AttributeOverride(name = "quotaSubtract", column = @Column(name = "quota_subtract", precision = 131089, scale = 0)),
			@AttributeOverride(name = "quotaFreez", column = @Column(name = "quota_freez", precision = 131089, scale = 0)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 521)),
			@AttributeOverride(name = "lastModifyDat", column = @Column(name = "last_modify_dat", length = 35)),
			@AttributeOverride(name = "lastModifyUuid", column = @Column(name = "last_modify_uuid", length = 36)) })
	public VSysUserId getId() {
		return this.id;
	}

	public void setId(VSysUserId id) {
		this.id = id;
	}

}
