package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-13 2:42:12 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUserSendingWorking generated by hbm2java
 */
@Entity
@Table(name = "v_user_sending_working", schema = "public")
public class VUserSendingWorking implements java.io.Serializable {

	private VUserSendingWorkingId id;

	public VUserSendingWorking() {
	}

	public VUserSendingWorking(VUserSendingWorkingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "sendingCount", column = @Column(name = "sending_count")),
			@AttributeOverride(name = "id", column = @Column(name = "id", length = 36)),
			@AttributeOverride(name = "sendWeighting", column = @Column(name = "send_weighting", precision = 131089, scale = 0)) })
	public VUserSendingWorkingId getId() {
		return this.id;
	}

	public void setId(VUserSendingWorkingId id) {
		this.id = id;
	}

}
