package com.cqqyd2014.hibernate.entities;
// Generated 2018-1-24 14:27:47 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUserPar generated by hbm2java
 */
@Entity
@Table(name = "v_user_par", schema = "public")
public class VUserPar implements java.io.Serializable {

	private VUserParId id;

	public VUserPar() {
	}

	public VUserPar(VUserParId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", length = 45)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 45)),
			@AttributeOverride(name = "parCode", column = @Column(name = "par_code", length = 45)),
			@AttributeOverride(name = "parDesc", column = @Column(name = "par_desc", length = 512)),
			@AttributeOverride(name = "parValue", column = @Column(name = "par_value")) })
	public VUserParId getId() {
		return this.id;
	}

	public void setId(VUserParId id) {
		this.id = id;
	}

}
