package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-5 14:48:25 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name = "warehouse", schema = "public")
public class Warehouse implements java.io.Serializable {

	private WarehouseId id;
	private String whName;
	private Integer priority;
	private String ccmcShort;
	private Boolean effective;

	public Warehouse() {
	}

	public Warehouse(WarehouseId id) {
		this.id = id;
	}

	public Warehouse(WarehouseId id, String whName, Integer priority, String ccmcShort, Boolean effective) {
		this.id = id;
		this.whName = whName;
		this.priority = priority;
		this.ccmcShort = ccmcShort;
		this.effective = effective;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 45)),
			@AttributeOverride(name = "whId", column = @Column(name = "wh_id", nullable = false, length = 6)) })
	public WarehouseId getId() {
		return this.id;
	}

	public void setId(WarehouseId id) {
		this.id = id;
	}

	@Column(name = "wh_name", length = 45)
	public String getWhName() {
		return this.whName;
	}

	public void setWhName(String whName) {
		this.whName = whName;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "ccmc_short", length = 45)
	public String getCcmcShort() {
		return this.ccmcShort;
	}

	public void setCcmcShort(String ccmcShort) {
		this.ccmcShort = ccmcShort;
	}

	@Column(name = "effective")
	public Boolean getEffective() {
		return this.effective;
	}

	public void setEffective(Boolean effective) {
		this.effective = effective;
	}

}
