package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-5 14:48:25 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WxInput generated by hbm2java
 */
@Entity
@Table(name = "wx_input", schema = "public")
public class WxInput implements java.io.Serializable {

	private String uuid;
	private String fromUsername;
	private Date inputTime;
	private String txt;
	private String toUsername;
	private String nickname;
	private Integer msgId;
	private String msgFrom;
	private String imgMediaId;
	private String msgType;
	private Date msgTime;
	private String imgUrl;
	private Long imgBin;
	private String comId;

	public WxInput() {
	}

	public WxInput(String uuid) {
		this.uuid = uuid;
	}

	public WxInput(String uuid, String fromUsername, Date inputTime, String txt, String toUsername, String nickname,
			Integer msgId, String msgFrom, String imgMediaId, String msgType, Date msgTime, String imgUrl, Long imgBin,
			String comId) {
		this.uuid = uuid;
		this.fromUsername = fromUsername;
		this.inputTime = inputTime;
		this.txt = txt;
		this.toUsername = toUsername;
		this.nickname = nickname;
		this.msgId = msgId;
		this.msgFrom = msgFrom;
		this.imgMediaId = imgMediaId;
		this.msgType = msgType;
		this.msgTime = msgTime;
		this.imgUrl = imgUrl;
		this.imgBin = imgBin;
		this.comId = comId;
	}

	@Id

	@Column(name = "uuid", unique = true, nullable = false, length = 45)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "from_username", length = 45)
	public String getFromUsername() {
		return this.fromUsername;
	}

	public void setFromUsername(String fromUsername) {
		this.fromUsername = fromUsername;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "input_time", length = 35)
	public Date getInputTime() {
		return this.inputTime;
	}

	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	@Column(name = "txt")
	public String getTxt() {
		return this.txt;
	}

	public void setTxt(String txt) {
		this.txt = txt;
	}

	@Column(name = "to_username", length = 45)
	public String getToUsername() {
		return this.toUsername;
	}

	public void setToUsername(String toUsername) {
		this.toUsername = toUsername;
	}

	@Column(name = "nickname", length = 45)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "msg_id")
	public Integer getMsgId() {
		return this.msgId;
	}

	public void setMsgId(Integer msgId) {
		this.msgId = msgId;
	}

	@Column(name = "msg_from", length = 45)
	public String getMsgFrom() {
		return this.msgFrom;
	}

	public void setMsgFrom(String msgFrom) {
		this.msgFrom = msgFrom;
	}

	@Column(name = "img_media_id", length = 90)
	public String getImgMediaId() {
		return this.imgMediaId;
	}

	public void setImgMediaId(String imgMediaId) {
		this.imgMediaId = imgMediaId;
	}

	@Column(name = "msg_type", length = 45)
	public String getMsgType() {
		return this.msgType;
	}

	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "msg_time", length = 35)
	public Date getMsgTime() {
		return this.msgTime;
	}

	public void setMsgTime(Date msgTime) {
		this.msgTime = msgTime;
	}

	@Column(name = "img_url", length = 512)
	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	@Column(name = "img_bin")
	public Long getImgBin() {
		return this.imgBin;
	}

	public void setImgBin(Long imgBin) {
		this.imgBin = imgBin;
	}

	@Column(name = "com_id", length = 45)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

}
