package com.cqqyd2014.hibernate.entities;
// Generated 2017-12-16 20:52:26 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WxUser generated by hbm2java
 */
@Entity
@Table(name = "wx_user", schema = "public")
public class WxUser implements java.io.Serializable {

	private String openId;
	private String nickname;
	private Integer sex;
	private String city;
	private String country;
	private String provice;
	private String language;
	private String headimgurl;
	private String remark;
	private String groupid;
	private Date subscribeTime;
	private String comId;
	private Boolean sub;

	public WxUser() {
	}

	public WxUser(String openId) {
		this.openId = openId;
	}

	public WxUser(String openId, String nickname, Integer sex, String city, String country, String provice,
			String language, String headimgurl, String remark, String groupid, Date subscribeTime, String comId,
			Boolean sub) {
		this.openId = openId;
		this.nickname = nickname;
		this.sex = sex;
		this.city = city;
		this.country = country;
		this.provice = provice;
		this.language = language;
		this.headimgurl = headimgurl;
		this.remark = remark;
		this.groupid = groupid;
		this.subscribeTime = subscribeTime;
		this.comId = comId;
		this.sub = sub;
	}

	@Id

	@Column(name = "open_id", unique = true, nullable = false, length = 45)
	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@Column(name = "nickname")
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "provice", length = 45)
	public String getProvice() {
		return this.provice;
	}

	public void setProvice(String provice) {
		this.provice = provice;
	}

	@Column(name = "language", length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "headimgurl")
	public String getHeadimgurl() {
		return this.headimgurl;
	}

	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

	@Column(name = "remark", length = 45)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "groupid", length = 45)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "subscribe_time", length = 35)
	public Date getSubscribeTime() {
		return this.subscribeTime;
	}

	public void setSubscribeTime(Date subscribeTime) {
		this.subscribeTime = subscribeTime;
	}

	@Column(name = "com_id", length = 45)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "sub")
	public Boolean getSub() {
		return this.sub;
	}

	public void setSub(Boolean sub) {
		this.sub = sub;
	}

}
