package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-6 13:56:00 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DeliverD generated by hbm2java
 */
@Entity
@Table(name = "deliver_d", schema = "public")
public class DeliverD implements java.io.Serializable {

	private DeliverDId id;
	private String orderNo;
	private String seq;
	private String goodsId;
	private String goodsBarcode;
	private BigDecimal num;
	private BigDecimal netWeight;
	private BigDecimal grossWeight;
	private BigDecimal packageWeight;

	public DeliverD() {
	}

	public DeliverD(DeliverDId id, String orderNo, String seq, String goodsId, String goodsBarcode) {
		this.id = id;
		this.orderNo = orderNo;
		this.seq = seq;
		this.goodsId = goodsId;
		this.goodsBarcode = goodsBarcode;
	}

	public DeliverD(DeliverDId id, String orderNo, String seq, String goodsId, String goodsBarcode, BigDecimal num,
			BigDecimal netWeight, BigDecimal grossWeight, BigDecimal packageWeight) {
		this.id = id;
		this.orderNo = orderNo;
		this.seq = seq;
		this.goodsId = goodsId;
		this.goodsBarcode = goodsBarcode;
		this.num = num;
		this.netWeight = netWeight;
		this.grossWeight = grossWeight;
		this.packageWeight = packageWeight;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "uuid", column = @Column(name = "uuid", nullable = false, length = 36)) })
	public DeliverDId getId() {
		return this.id;
	}

	public void setId(DeliverDId id) {
		this.id = id;
	}

	@Column(name = "order_no", nullable = false, length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "seq", nullable = false, length = 4)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "goods_id", nullable = false, length = 45)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "goods_barcode", nullable = false, length = 22)
	public String getGoodsBarcode() {
		return this.goodsBarcode;
	}

	public void setGoodsBarcode(String goodsBarcode) {
		this.goodsBarcode = goodsBarcode;
	}

	@Column(name = "num", precision = 131089, scale = 0)
	public BigDecimal getNum() {
		return this.num;
	}

	public void setNum(BigDecimal num) {
		this.num = num;
	}

	@Column(name = "net_weight", precision = 131089, scale = 0)
	public BigDecimal getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(BigDecimal netWeight) {
		this.netWeight = netWeight;
	}

	@Column(name = "gross_weight", precision = 131089, scale = 0)
	public BigDecimal getGrossWeight() {
		return this.grossWeight;
	}

	public void setGrossWeight(BigDecimal grossWeight) {
		this.grossWeight = grossWeight;
	}

	@Column(name = "package_weight", precision = 131089, scale = 0)
	public BigDecimal getPackageWeight() {
		return this.packageWeight;
	}

	public void setPackageWeight(BigDecimal packageWeight) {
		this.packageWeight = packageWeight;
	}

}
