package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-6 13:56:00 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FinanceGoodsPriceId generated by hbm2java
 */
@Embeddable
public class FinanceGoodsPriceId implements java.io.Serializable {

	private String goodsId;
	private String comId;
	private Date startDat;

	public FinanceGoodsPriceId() {
	}

	public FinanceGoodsPriceId(String goodsId, String comId, Date startDat) {
		this.goodsId = goodsId;
		this.comId = comId;
		this.startDat = startDat;
	}

	@Column(name = "goods_id", nullable = false, length = 45)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "com_id", nullable = false, length = 4)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "start_dat", nullable = false, length = 35)
	public Date getStartDat() {
		return this.startDat;
	}

	public void setStartDat(Date startDat) {
		this.startDat = startDat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FinanceGoodsPriceId))
			return false;
		FinanceGoodsPriceId castOther = (FinanceGoodsPriceId) other;

		return ((this.getGoodsId() == castOther.getGoodsId()) || (this.getGoodsId() != null
				&& castOther.getGoodsId() != null && this.getGoodsId().equals(castOther.getGoodsId())))
				&& ((this.getComId() == castOther.getComId()) || (this.getComId() != null
						&& castOther.getComId() != null && this.getComId().equals(castOther.getComId())))
				&& ((this.getStartDat() == castOther.getStartDat()) || (this.getStartDat() != null
						&& castOther.getStartDat() != null && this.getStartDat().equals(castOther.getStartDat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGoodsId() == null ? 0 : this.getGoodsId().hashCode());
		result = 37 * result + (getComId() == null ? 0 : this.getComId().hashCode());
		result = 37 * result + (getStartDat() == null ? 0 : this.getStartDat().hashCode());
		return result;
	}

}
