package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-6 13:56:00 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinanceGoodsPrice generated by hbm2java
 */
@Entity
@Table(name = "finance_goods_price", schema = "public")
public class FinanceGoodsPrice implements java.io.Serializable {

	private FinanceGoodsPriceId id;
	private Date endDat;
	private BigDecimal price;

	public FinanceGoodsPrice() {
	}

	public FinanceGoodsPrice(FinanceGoodsPriceId id) {
		this.id = id;
	}

	public FinanceGoodsPrice(FinanceGoodsPriceId id, Date endDat, BigDecimal price) {
		this.id = id;
		this.endDat = endDat;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", nullable = false, length = 45)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "startDat", column = @Column(name = "start_dat", nullable = false, length = 35)) })
	public FinanceGoodsPriceId getId() {
		return this.id;
	}

	public void setId(FinanceGoodsPriceId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_dat", length = 35)
	public Date getEndDat() {
		return this.endDat;
	}

	public void setEndDat(Date endDat) {
		this.endDat = endDat;
	}

	@Column(name = "price", precision = 131089, scale = 0)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
