package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-6 13:56:00 by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LogisticsBillPrintTemplet generated by hbm2java
 */
@Entity
@Table(name = "logistics_bill_print_templet", schema = "public")
public class LogisticsBillPrintTemplet implements java.io.Serializable {

	private LogisticsBillPrintTempletId id;
	private String logisticsBillDesc;
	private Boolean effective;
	private String printType;

	public LogisticsBillPrintTemplet() {
	}

	public LogisticsBillPrintTemplet(LogisticsBillPrintTempletId id) {
		this.id = id;
	}

	public LogisticsBillPrintTemplet(LogisticsBillPrintTempletId id, String logisticsBillDesc, Boolean effective,
			String printType) {
		this.id = id;
		this.logisticsBillDesc = logisticsBillDesc;
		this.effective = effective;
		this.printType = printType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "logisticsCode", column = @Column(name = "logistics_code", nullable = false, length = 10)),
			@AttributeOverride(name = "logisticsBillCode", column = @Column(name = "logistics_bill_code", nullable = false, length = 4)) })
	public LogisticsBillPrintTempletId getId() {
		return this.id;
	}

	public void setId(LogisticsBillPrintTempletId id) {
		this.id = id;
	}

	@Column(name = "logistics_bill_desc", length = 45)
	public String getLogisticsBillDesc() {
		return this.logisticsBillDesc;
	}

	public void setLogisticsBillDesc(String logisticsBillDesc) {
		this.logisticsBillDesc = logisticsBillDesc;
	}

	@Column(name = "effective")
	public Boolean getEffective() {
		return this.effective;
	}

	public void setEffective(Boolean effective) {
		this.effective = effective;
	}

	@Column(name = "print_type", length = 4)
	public String getPrintType() {
		return this.printType;
	}

	public void setPrintType(String printType) {
		this.printType = printType;
	}

}
