package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-6 13:56:00 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuotaTrans generated by hbm2java
 */
@Entity
@Table(name = "quota_trans", schema = "public")
public class QuotaTrans implements java.io.Serializable {

	private QuotaTransId id;
	private Date opTime;
	private BigDecimal beginAmount;
	private BigDecimal transAmount;
	private BigDecimal endAmount;
	private String transType;
	private String memo;
	private String orderno;
	private BigDecimal beginFreezAmount;
	private BigDecimal transFreezAmount;
	private BigDecimal endFreezAmount;
	private String wrongUuid;
	private String userid;
	private String opUserid;
	private String status;

	public QuotaTrans() {
	}

	public QuotaTrans(QuotaTransId id) {
		this.id = id;
	}

	public QuotaTrans(QuotaTransId id, Date opTime, BigDecimal beginAmount, BigDecimal transAmount,
			BigDecimal endAmount, String transType, String memo, String orderno, BigDecimal beginFreezAmount,
			BigDecimal transFreezAmount, BigDecimal endFreezAmount, String wrongUuid, String userid, String opUserid,
			String status) {
		this.id = id;
		this.opTime = opTime;
		this.beginAmount = beginAmount;
		this.transAmount = transAmount;
		this.endAmount = endAmount;
		this.transType = transType;
		this.memo = memo;
		this.orderno = orderno;
		this.beginFreezAmount = beginFreezAmount;
		this.transFreezAmount = transFreezAmount;
		this.endFreezAmount = endFreezAmount;
		this.wrongUuid = wrongUuid;
		this.userid = userid;
		this.opUserid = opUserid;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", nullable = false, length = 4)),
			@AttributeOverride(name = "uuid", column = @Column(name = "uuid", nullable = false, length = 36)) })
	public QuotaTransId getId() {
		return this.id;
	}

	public void setId(QuotaTransId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "op_time", length = 35)
	public Date getOpTime() {
		return this.opTime;
	}

	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	@Column(name = "begin_amount", precision = 131089, scale = 0)
	public BigDecimal getBeginAmount() {
		return this.beginAmount;
	}

	public void setBeginAmount(BigDecimal beginAmount) {
		this.beginAmount = beginAmount;
	}

	@Column(name = "trans_amount", precision = 131089, scale = 0)
	public BigDecimal getTransAmount() {
		return this.transAmount;
	}

	public void setTransAmount(BigDecimal transAmount) {
		this.transAmount = transAmount;
	}

	@Column(name = "end_amount", precision = 131089, scale = 0)
	public BigDecimal getEndAmount() {
		return this.endAmount;
	}

	public void setEndAmount(BigDecimal endAmount) {
		this.endAmount = endAmount;
	}

	@Column(name = "trans_type", length = 4)
	public String getTransType() {
		return this.transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}

	@Column(name = "memo", length = 512)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "orderno", length = 20)
	public String getOrderno() {
		return this.orderno;
	}

	public void setOrderno(String orderno) {
		this.orderno = orderno;
	}

	@Column(name = "begin_freez_amount", precision = 131089, scale = 0)
	public BigDecimal getBeginFreezAmount() {
		return this.beginFreezAmount;
	}

	public void setBeginFreezAmount(BigDecimal beginFreezAmount) {
		this.beginFreezAmount = beginFreezAmount;
	}

	@Column(name = "trans_freez_amount", precision = 131089, scale = 0)
	public BigDecimal getTransFreezAmount() {
		return this.transFreezAmount;
	}

	public void setTransFreezAmount(BigDecimal transFreezAmount) {
		this.transFreezAmount = transFreezAmount;
	}

	@Column(name = "end_freez_amount", precision = 131089, scale = 0)
	public BigDecimal getEndFreezAmount() {
		return this.endFreezAmount;
	}

	public void setEndFreezAmount(BigDecimal endFreezAmount) {
		this.endFreezAmount = endFreezAmount;
	}

	@Column(name = "wrong_uuid", length = 36)
	public String getWrongUuid() {
		return this.wrongUuid;
	}

	public void setWrongUuid(String wrongUuid) {
		this.wrongUuid = wrongUuid;
	}

	@Column(name = "userid", length = 36)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "op_userid", length = 36)
	public String getOpUserid() {
		return this.opUserid;
	}

	public void setOpUserid(String opUserid) {
		this.opUserid = opUserid;
	}

	@Column(name = "status", length = 4)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
