package com.cqqyd2014.hibernate.entities;
// Generated 2017-11-6 13:56:00 by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDeliverD generated by hbm2java
 */
@Entity
@Table(name = "v_deliver_d", schema = "public")
public class VDeliverD implements java.io.Serializable {

	private VDeliverDId id;

	public VDeliverD() {
	}

	public VDeliverD(VDeliverDId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "effective", column = @Column(name = "effective")),
			@AttributeOverride(name = "sended", column = @Column(name = "sended")),
			@AttributeOverride(name = "deliverBillStatus", column = @Column(name = "deliver_bill_status", length = 4)),
			@AttributeOverride(name = "whName", column = @Column(name = "wh_name", length = 45)),
			@AttributeOverride(name = "whId", column = @Column(name = "wh_id", length = 6)),
			@AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "deliverExpressComName", column = @Column(name = "deliver_express_com_name", length = 45)),
			@AttributeOverride(name = "deliverExpressCom", column = @Column(name = "deliver_express_com", length = 45)),
			@AttributeOverride(name = "deliverExpressNo", column = @Column(name = "deliver_express_no", length = 45)),
			@AttributeOverride(name = "deliverExpressVehicle", column = @Column(name = "deliver_express_vehicle", length = 4)),
			@AttributeOverride(name = "goodsBarcode", column = @Column(name = "goods_barcode", length = 22)),
			@AttributeOverride(name = "orderNo", column = @Column(name = "order_no", length = 20)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq", length = 4)),
			@AttributeOverride(name = "goodsId", column = @Column(name = "goods_id", length = 45)),
			@AttributeOverride(name = "CName", column = @Column(name = "c_name", length = 100)),
			@AttributeOverride(name = "netWeight", column = @Column(name = "net_weight", precision = 131089, scale = 0)),
			@AttributeOverride(name = "grossWeight", column = @Column(name = "gross_weight", precision = 131089, scale = 0)),
			@AttributeOverride(name = "deliverDUuid", column = @Column(name = "deliver_d_uuid", length = 36)),
			@AttributeOverride(name = "packageWeight", column = @Column(name = "package_weight", precision = 131089, scale = 0)),
			@AttributeOverride(name = "deliverNo", column = @Column(name = "deliver_no", length = 45)),
			@AttributeOverride(name = "unit", column = @Column(name = "unit", length = 90)) })
	public VDeliverDId getId() {
		return this.id;
	}

	public void setId(VDeliverDId id) {
		this.id = id;
	}

}
